Minify with terser
happy-geeks/wiser pull request #115
Opened 2022-07-28 12:11 UTC by HansJuice

Enables the minification of JavaScript files created in the Templates module using terser, a Node.js package, using the Process API of .NET.

https://app.asana.com/0/1201027711166952/1202642897878033

2022-08-03 11:36 UTC, GilianJuice requested changes

2022-08-15 07:03 UTC, HansJuice commented on Api/Modules/Templates/Services/TemplatesService.cs
> +                };
Dit heb ik inderdaad niet goed aangepast. Het idee was om de melding te loggen, maar daar heb ik blijkbaar iets niet goed gedaan. Ik heb mezelf gepland om dit aan te passen.

2022-08-15 07:04 UTC, HansJuice commented on Api/Modules/Templates/Services/TemplatesService.cs
> +            return (successful, output);
De `MinifyJavaScriptWithTerser` functie kan inderdaad null teruggeven, maar dit zal niet gebeuren zonder dat `successful` op false zal staan. Op de plek waar het script wordt aangeroepen wordt vervolgens gekeken of de minification successful was, en zo niet, dan wordt NUglify gebruikt, en als _die_ mislukt, dan wordt de template non-minified opgeslagen zodat werk niet verloren gaat.

M.a.w., er gaat geen werk verloren als het minifiën met terser mislukt, maar als je toch liever hebt dat de functie altijd het originele script teruggeeft als het fout gaat, dan zal ik dit nog aanpassen.

2022-08-18 10:32 UTC, HansJuice commented on Api/Modules/Templates/Services/TemplatesService.cs
> +                };
De ErrorDataReceived event logged nu de error (als een warning) en zet successful op false. Dit bepaalt dus niet langer de output.

2022-08-18 10:34 UTC, HansJuice commented on Api/Modules/Templates/Services/TemplatesService.cs
> +            return (successful, output);
Ik heb ervoor gezorgd dat als de output null of leeg is, dat het originele script toch teruggegeven wordt. Dit is nu eigenlijk alleen voor de gevallen dat terser geen error teruggeeft, maar wel een leeg resultaat. Dat zou niet voor mogen komen, maar nu gaat er in ieder geval zeker geen werk verloren.

2022-08-23 06:47 UTC, rvdgraaf approved these changes

2022-08-23 06:47 UTC, merged