Feature/front end new link tab
happy-geeks/wiser pull request #125
Opened 2022-08-16 08:07 UTC by ericarts

In de admin module is door Bjorn een nieuwe tab toegevoegd (nieuwe link toevoegen).
De tab + bijhorende popup zijn nu beter gestyled.

2022-08-19 06:33 UTC, HansJuice commented
Eric, ik zie dat er conflicten zijn met o.a. de TemplatesService.cs uit de API. Ik denk dat je misschien eerst de develop branch moeten mergen naar deze branch om de conflicten op te lossen. Als dat niet lukt, laat dat dan even weten want dan er een developer even naar kijken.

2022-08-19 06:34 UTC, HansJuice requested changes
Eric, ik zie dat er merge conflicten zijn. Ik denk dat je misschien eerst de develop branch moeten mergen naar deze branch om de conflicten op te lossen. Als dat niet lukt, laat dat dan even weten want dan er een developer even naar kijken.

2022-08-26 08:04 UTC, HansJuice commented
Ik krijg dit niet zomaar gemerged. Index.cshtml bevat 140+ merge conflicten, waardoor het onmogelijk wordt om dit fatsoenlijk te mergen naar develop. Ik zal hier nog een keer dieper in duiken om te kijken of ik een oplossing kan vinden.

2023-02-24 16:31 UTC, GilianJuice commented
Ik heb de merge conflicten opgelost, was uiteindelijk toch niet zo moeilijk. Ik heb ook wat bugs opgelost en code-verbeteringen doorgevoerd. Echter ben ik nog niet klaar hiermee, dus graag deze pull request nog niet mergen.

2023-03-01 16:27 UTC, GilianJuice commented
Dit is nu afgemaakt. Deze mag nu nagekeken worden en gemerged indien goedgekeurd.

2023-03-02 11:19 UTC, MarkVanDijkHG requested changes
Paar wijzigingen om te controleren/verbeteren en veel punten die zijn ontstaan tijdens de merge van de HTML.

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/LinkSettingsModel.js
> +
Graag 1 witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/WiserLinkTab.js
> +                placeholder: "Select gewenste link...",
Graag hier de placeholder tekst verbeteren.

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/Admin.js
> +                    this.wiserLinkTab.beforeSave();
Hoeft hier geen await gebruikt te worden zoals bij de andere tabbladen?

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                    <div class="itemmodule-tree-view-mode hidden" data-module-type-filter="DynamicItems" style="width: 20%;">
Klopt het dat deze classes zijn samengevoegd?

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                        <label>Tabelnaam voorvoegsel </label>
Spatie op het einde is denk ik overbodig

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                <div class="item" style="width:  25%;">
Teveel witruimte

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                        <label for="input-type">Icoontoevoegen</label>
Spatie is hier weg gevallen

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                            </div><div class="item" style="width: 50%;" data-visible="Input SecureInput TextBox GpsLocation HtmlEditor ColorPicker ComboBox DataSelecto
Mag weer op 2 regels

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                            </div><div class="item" data-invisible="FileUpload ImageUpload DataSelector SubEntitiesGrid">
Mag weer op 2 regels

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
2 overbodige witregels

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
2 overbodige witregels

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                            <div class="item " data-visible="CheckBox">
Onnodige spatie

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                                        <div class="item " style="width: 25%;">
Onnodige spatie

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                                        <div class="item " style="width: 50%;">
Onnodige spatie

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +                                                                        <div class="item " style="width: 25%;">
Onnodige spatie

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-02 11:19 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
> +
Overbodige witregel

2023-03-06 15:26 UTC, MarkVanDijkHG approved these changes

2023-03-06 15:27 UTC, merged