Added save template action to save button.
happy-geeks/wiser pull request #130
Opened 2022-08-22 14:44 UTC by MaxBeekmans

Added the save template action to the save button in the html editor.
This will save the html as well as the template when pressing the save button in the html editor.
The same feature can be triggered through the Ctrl-S keyboard action.

[Asana task](https://app.asana.com/0/1201027711166952/1202666985299717/f)

2022-08-24 11:42 UTC, rvdgraaf requested changes
Zie opmerking

2022-08-24 11:42 UTC, rvdgraaf commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    await this.base.setHtmlAndSave(codeMirrorInstance.getValue());
Klopt het dat het de getValue() achter de codeMirrorInstance staat? In de functie setHtmlAndSave staat er vervolgens ook weer de getValue() achter. Op regel 1259 wordt "cm" meegestuurd, een instantie van codemirror en hier wordt codeMirrorInstance.getValue() meegestuurd.

2022-08-24 12:04 UTC, MaxBeekmans commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    await this.base.setHtmlAndSave(codeMirrorInstance.getValue());
Hoi Rinus, Ik heb de extra .getValue() weggehaald.

2022-08-26 07:06 UTC, HansJuice approved these changes

2022-09-06 07:08 UTC, merged