Feature/dynamisch content element verwijderen
happy-geeks/wiser pull request #140
Opened 2022-09-12 14:35 UTC by JeremyMullerr

Het is nu mogelijk een dynamic content element te verwijderen

2022-09-13 13:39 UTC, GilianJuice requested changes
Je hebt de PR nu gemaakt op de branch `main`. Pull requests moeten altijd via de branch `develop` gaan bij ons. Graag aanpassen (je hoeft niet een nieuwe PR te maken, je kunt de branch gewoon hier wijzigen). Verder, zie ook mijn andere opmerking.

2022-09-13 13:39 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                } catch (exception){
Deze try/catch heeft niet zoveel zin. Dat werkt alleen als je `await` gebruikt. Je gebruikt nu de `then` functie van de promise, als je fouten daarvan wilt opvangen, moet je ook de `catch` functie gebruiken (of `fail` in het geval van jQuery, wat we hier gebruiken). Dus zoiets:
```javascript
Wiser.api({
    url: `${this.settings.wiserApiRoot}dynamic-content/${data.id}`,
    dataType: "json",
    type: "DELETE",
    contentType: "application/json"
}).then(() => {
    this.dynamicContentGrid.dataSource.read();
}).fail((jqXhr, textStatus, errorThrown) => {
    console.error(errorThrown);
    kendo.alert("Er is iets fout gegaan tijdens het verwijderen van dit item. Probeer het a.u.b. nogmaals of neem contact op met ons.");
});
```

Graag zo maken ipv try/catch. Normaal gesproken had ik gezegd om juist async/await te gebruiken, maar in dit geval gaat dat niet omdat knoppen van Kendo UI daar niet mee om kunnen gaan.
Verder ben je ook een puntkomma vergeten aan het einde van regel 1384.

2022-09-13 13:40 UTC, GilianJuice commented
En hier heb je ook geen URL naar Asana gezet, graag ook nog toevoegen.

2022-09-13 13:46 UTC, GilianJuice commented
Oh en je hebt allerlei bestanden uit de map `.idea` van Rider gecommit, dat is ook niet de bedoeling. Ik zie dat deze nog niet in de gitignore stond van dit project, ik heb die nu toegevoegd in de develop branch. Kun je die bestanden weer weghalen, zodat ze niet in de develop branch komen?

Kun je daarnaast ook deze handleiding nog volgen voor de globale git ignore? https://app.nuclino.com/Happy-Geeks/Development/Instellingen-voor-Git-87f5efd5-b083-49ea-b34d-4f39e2739d7c

2022-09-14 08:45 UTC, JeremyMullerr commented
Benodigde aanpassingen zijn gedaan
Asana URL: https://app.asana.com/0/1202870143919582/1202879712279712

2022-09-14 11:37 UTC, GilianJuice requested changes
Nog een paar kleine opmerkingen, daarna is het goed.

2022-09-14 11:37 UTC, GilianJuice commented on .gitignore
> +.idea/.idea.Wiser/.idea/workspace.xml
Deze gitignore is niet nodig, ik heb al de gehele `.idea` map toegevoegd aan de gitignore.

2022-09-14 11:37 UTC, GilianJuice commented on Api/Modules/Templates/Services/DataLayer/DynamicContentDataService.cs
> +        public async Task DeleteAsync(int contentId)
Graag hier nog `/// <inheritdoc />` toevoegen boven de functie, zodat de documentatie die in de interface staat wordt overgenomen.

2022-09-14 11:37 UTC, GilianJuice commented on Api/Modules/Templates/Services/DynamicContentService.cs
> +        public async Task<ServiceResult<bool>> DeleteAsync(int contentId)
Graag hier nog `/// <inheritdoc />` toevoegen boven de functie, zodat de documentatie die in de interface staat wordt overgenomen.

2022-09-14 12:08 UTC, GilianJuice approved these changes

2022-09-14 12:08 UTC, merged