Feature/required name dynamic content
happy-geeks/wiser pull request #151
Opened 2022-10-04 12:50 UTC by JeremyMullerr

Er kon geen naam ingevuld worden in een dynamische content template. Hierdoor was de naam een whitespace. Ik heb nu toegevoegd dat je een melding krijgt als er geen naam ingevuld is. Hierdoor is een naam invullen nu verplicht 

Asana ticket:
https://app.asana.com/0/1201027711166952/1202988286054836

2022-10-05 07:59 UTC, MarkVanDijkHG requested changes

2022-10-05 07:59 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                    window.popupNotification.show(`Geen naam ingevoerd! Vul een naam in.`, "info");
Graag een return statement hier gebruiken om het opslaan te annuleren. Dan is de "else" ook niet meer nodig, momenteel staat er ook nog code buiten de "else" die ook niet uitgevoerd moeten worden. Vergeet hierbij niet dat voor de return ook saving flag en process worden uitgezet (zie onderaan in de functie).

2022-10-05 07:59 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                    window.popupNotification.show(`Geen naam ingevoerd! Vul een naam in.`, "info");
Graag kendo.alert gebruiken voor de popup in plaats van window.popupNotification. De notificatie verdwijnt automatisch waardoor mensen dit kunnen missen.

2022-10-05 08:00 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                    window.popupNotification.show(`Geen naam ingevoerd! Vul een naam in.`, "info");
Graag ook spatie zetten tussen `if (!title)` en `{`, zodat het consequent is met de rest van de code.

2022-10-10 08:44 UTC, JeremyMullerr commented
Benodigde aanpassingen gedaan.

2022-10-11 12:29 UTC, GilianJuice approved these changes

2022-10-11 12:29 UTC, merged