Cache URL will now be stored in localstorage
happy-geeks/wiser pull request #163
Opened 2022-10-27 12:44 UTC by JeremyMullerr

De cache URL wordt nu ingevuld in het cache URL veld indien er een cache URL in de localstorage staat.

Asana ticket: https://app.asana.com/0/1201027711166952/1203158028215056

2022-10-28 10:16 UTC, HansJuice requested changes

2022-10-28 10:16 UTC, HansJuice commented on FrontEnd/Core/Scripts/main.js
> +                        if (localStorage.getItem("clear_cache_url")){
Graat een spatie zetten tussen het sluithaakje `)` en de accolade `{`. Dan blijft het consistent met met de rest van het script.

2022-11-01 09:56 UTC, JeremyMullerr commented
Benodigde wijzigingen gemaakt

2022-11-08 12:58 UTC, GilianJuice approved these changes

2022-11-08 12:58 UTC, merged