Dashboard development
happy-geeks/wiser pull request #176
Opened 2022-11-10 14:58 UTC by HansJuice

* GCL is now used to check and create/update tables.
* Closing and opening tiles now works properly.
* Updated usages of "wiser_dashboard" to use WiserTableNames constant.
* Added UpdateLog.html again.
* Disabled subscription and dataselector tiles (for now).
* Updated CreateTables.sql and InsertInitialData.sql.

Accompanying PR for GCL: https://github.com/happy-geeks/geeks-core-library/pull/217

Asana: https://app.asana.com/0/1201027711166952/1203237258080986

2022-11-14 15:36 UTC, GilianJuice requested changes

2022-11-14 15:36 UTC, GilianJuice commented on Api/Modules/Customers/Controllers/UsersController.cs
> +        [HttpGet, Route("dashboard-settings")]
We doen bij Wiser altijd attributen los van elkaar op losse regels, zou je dat hier aub ook willen doen? Daarnaast graag ook het attribuut `ProducesResponseType` gebruiken om aan te geven wat de functie teruggeeft, dat is belangrijk voor de Swagger documentatie.

2022-11-14 15:36 UTC, GilianJuice commented on Api/Modules/Dashboard/Controllers/DashboardController.cs
> +    [HttpPut, Route("services/{id:int}/extra-run/{state:bool}")]
Hier graag ook attributen scheiden op meerdere regels en `ProducesResponseType` gebruiken. Ook graag commentaar toevoegen boven de functie.

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        /*{
Graag geen code in commentaar laten staan zonder goede reden.

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        }*/
Graag geen code in commentaar laten staan zonder goede reden.

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +                dataBound: this.setServiceState
Kun je hier nog `.bind(this)` aan toevoegen? Anders krijg je een andere context in die functie, wat in de toekomst voor verwarring kan zorgen.

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        setServiceState(e) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
>          async togglePauseService(e) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        async toggleExtraRunService(e) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
>          async openServiceLogs(e) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
>          async onPeriodFilterChange(event) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +                    content: "Het opslaan van het dashboard layout is mislukt."
Bij foutmeldingen graag altijd vermelden wat de gebruiker zelf kan doen om het probleem op te lossen, zelfs als het alleen iets is zoals "Probeer het a.u.b. opnieuw, of neem contact op met ons.".

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        async addTile(tileId) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        async removeTile(tileId) {
Kun je commentaar bij de functie toevoegen om te omschrijven wat die functie doet?

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Views/Dashboard/Index.cshtml
> +                                        @*<li>
Geen code in commentaar laten staan aub. Of als er een goede reden voor is om het wel te laten staan, dan die reden erbij zetten.

2022-11-14 15:36 UTC, GilianJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Waarom heb je dit bestand weer teruggezet? Ik heb dat al 2 keer verwijderd. Ik zie het nut van dit bestand niet in, hier staat alleen HTML in, waarom niet gewoon die HTML direct in de cshtml zetten?

Aan de inhoud te zien lijkt dit een soort release historie voor het dashboard te zijn (waarom? dat hebben we voor geen enkele module, waarom voor dashboard wel?). Als dat zo is, dan moet dit bestand sowieso niet in de root staan met deze naam, dan hoort die thuis in de map van de betreffende module.

Als dit wel een release historie is van Wiser algemeen, dan ook lijkt me dit niet handig. Wie gaat dit bijhouden? We zijn bij Wiser 1 juist gestopt met die release historie, omdat klanten die toch nooit lazen en dat elke keer veel tijd kostte om dat aan te vullen.

2022-11-15 08:07 UTC, HansJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Ik heb dit in het begin van de ontwikkeling met Ferry afgesproken om het zo te doen (dus dat het een los bestand is). Dan hoeft alleen het `UpdateLog.html` bestand aangepast te worden, en maakt het dus niet uit of de log bijgewerkt is tijdens het maken van een nieuwe release. De reden dat ik het in de root had gezet is omdat het een update log is voor heel Wiser, niet alleen van het dashboard, en omdat het dan niet zomaar uit te lezen is aangezien je bestanden die in de root staan niet los op kunt vragen (al zou dat niet echt een grote issue zijn). Het had echter wel in een andere sub-folder kunnen staan, dus misschien dat de root inderdaad niet de beste plek is.

Wie de updates bij gaat houden hebben we toen niet besproken, dus ik denk niet dat daar echt over nagedacht is. Ik ben het echter wel met je eens dat er waarschijnlijk maar heel weinig klanten zijn die echt de update log gaan lezen.

Wellicht kun je tijdens een standaardisatieoverleg dit op tafel leggen om te bespreken wat we hiermee gaan doen.

2022-11-15 13:50 UTC, GilianJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Bedankt voor de info. Ik heb het genoteerd als punt voor ons volgende standaardisatieoverleg.

2022-12-15 12:18 UTC, HansJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Heb je al de kans gehad om hier over te hebben tijdens een standaardisatieoverleg? Als we het dashboard af willen ronden dan moeten we weten wat we hiermee gaan doen. Dus of we het zo laten staan, of dat we de update log op een andere manier gaan bijhouden, of het hele update log stuk weghalen, etc.

2022-12-15 12:28 UTC, GilianJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Ja daar hebben we het over gehad, vergeten door te geven aan jou, sorry. Ferry had uitgelegd waar het voor bedoeld was. We gaan wel een updatelog bijhouden, maar dan alleen met grotere/belangrijke wijzigingen, niet alle bug fixes en dan een link erin naar GitHub waar mensen dan alle wijzigingen kunnen zien. We hadden besproken dat we de updatelog dan gewoon hard in de view zetten, dus niet meer in een apart HTML-bestand.

2022-12-15 12:47 UTC, HansJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Duidelijk. Ik ga proberen om het afronden van het dashboard ergens in te plannen en dan zal ik de update log ombouwen naar HTML direct in de view.

2022-12-15 16:09 UTC, GilianJuice commented
Ik heb functionaliteit toegevoegd aan deze PR, voor dit Asana-punt: https://app.asana.com/0/1201027711166952/1203098343839938

2022-12-16 16:21 UTC, HansJuice commented on Api/Modules/Customers/Controllers/UsersController.cs
> +        [HttpGet, Route("dashboard-settings")]
Dit is nu aangepast.

2022-12-16 16:22 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        /*{
Code is weggehaald. Ik had het laten staan omdat het een keer terugkomt, maar we kunnen het altijd terug uit GitHub halen wanneer het zover is.

2022-12-16 16:22 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        }*/
Code is weggehaald. Ik had het laten staan omdat het een keer terugkomt, maar we kunnen het altijd terug uit GitHub halen wanneer het zover is.

2022-12-16 16:22 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +                dataBound: this.setServiceState
`.bind(this)` is toegevoegd.

2022-12-16 16:23 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +                    content: "Het opslaan van het dashboard layout is mislukt."
Ik heb de foutmelding iets uitgebreid. Ik heb ook een try...catch om de API call heen gezet zodat andere errors ook afgevangen worden.

2022-12-16 16:23 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        async addTile(tileId) {
Commentaar is toegevoegd.

2022-12-16 16:24 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        async removeTile(tileId) {
Commentaar is toegevoegd.

2022-12-16 16:24 UTC, HansJuice commented on FrontEnd/Modules/Dashboard/Views/Dashboard/Index.cshtml
> +                                        @*<li>
HTML is weggehaald. Ik had het laten staan omdat het een keer terugkomt, maar we kunnen het altijd terug uit GitHub halen wanneer het zover is.

2022-12-16 16:24 UTC, HansJuice commented on FrontEnd/UpdateLog.html
> +﻿<div class="log-item">
Bestand UpdateLog.html is verwijderd, en de HTML is verplaatst naar de view.

2022-12-16 16:26 UTC, HansJuice commented
Ik heb diverse feedback punten opgelost. Sowieso alle punten van mij, maar ook een paar van stukken die Mark had gemaakt. Een aantal script functies moeten nog van commentaar voorzien worden, maar aangezien Mark die heeft gemaakt kan hij beter omschrijven wat die functies doen.

2022-12-20 10:20 UTC, MarkVanDijkHG commented on Api/Modules/Dashboard/Controllers/DashboardController.cs
> +    [HttpPut, Route("services/{id:int}/extra-run/{state:bool}")]
Attributen gescheiden, "ProducesResponseType" toegevoegd en voorzien van commentaar.

2022-12-20 10:20 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        setServiceState(e) {
Commentaar toegevoegd.

2022-12-20 10:20 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
>          async togglePauseService(e) {
Commentaar toegevoegd.

2022-12-20 10:20 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +        async toggleExtraRunService(e) {
Commentaar toegevoegd.

2022-12-20 10:20 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
>          async openServiceLogs(e) {
Commentaar toegevoegd.

2022-12-20 14:02 UTC, GilianJuice approved these changes

2022-12-20 14:02 UTC, merged