Item files can now have extra data
happy-geeks/wiser pull request #181
Opened 2022-11-15 16:42 UTC by GilianJuice

This is made so that we can use different alt texts per language per image on a website. But it can also be used for other things in the future.

Asana ticket: https://app.asana.com/0/1201027711166952/1202813905771955
Corresponding GCL PR: https://github.com/happy-geeks/geeks-core-library/pull/222

2022-11-16 07:14 UTC, MarkVanDijkHG approved these changes

2022-11-18 10:41 UTC, HansJuice requested changes
Issue in scripting en een inconsistentie in een aanpassing van `Index.cshtml`. Deze graag oplossen.

2022-11-18 10:41 UTC, HansJuice commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                                window.processing.removeProcess(process);
Gaat dit wel goed? De `process` variabele wordt binnen het `try` blok aangemaakt, dus ik denk niet dat die beschikbaar is in het `catch` blok.

2022-11-18 13:29 UTC, GilianJuice commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                                window.processing.removeProcess(process);
Je hebt gelijkt, dit klopte niet. Ik heb dit aangepast.

2022-11-18 13:30 UTC, GilianJuice commented on FrontEnd/Modules/DynamicItems/Views/DynamicItems/Index.cshtml
> +        <div class="product" data-item-id="#= itemId #" data-image-id="#: fileId #" data-item-link-id="#: itemLinkId #" data-file-name="#: name #" data-title="#: title #" data-entity-type="#: entityT
Ik had het inderdaad maar half gedaan zie ik, ik heb er nu overal `#:` van gemaakt in die template. (Het verschil is dat `#:` de HTML doet encoden en `#=` niet.

2022-12-13 09:44 UTC, merged