Added documentation for classes that didnt have it
happy-geeks/wiser pull request #183
Opened 2022-11-17 16:05 UTC by JeremyMullerr

A big part of the warnings are now gone by adding documentation to it.

Asana ticket:
https://app.asana.com/0/1201027711166952/1203272064316613

2022-11-18 08:32 UTC, HansJuice requested changes
Er zijn wat typefouten en grammaticafouten in de toegevoegde commentaar teksten, en een aantal stukjes code die in commentaar zijn gezet die waarschijnlijk gewoon weg moeten. Graag deze aanpassen.

Ook is er wat inconsistentie tussen de commentaren dat het soms wel met een punt eindigt en soms niet. Onze richtlijnen zeggen echter niks over het gebruik van punten bij commentaar, dus deze hoeft van mij niet per se.

Wat onze richtlijnen wel zeggen is dat commentaar niet nuttig is als het niks extra's beschrijft: `Voeg commentaar toe om dingen te verduidelijken, niet omdat het kan.` Bijvoorbeeld voor de class `TypeHelpers`: Daar staat nu `Class that contains Type Helpers`. Ik denk dat de naam van de class dat al duidelijk maakt, dus ik weet niet of het zo nuttig is om dat er in te zetten. Beschrijf dan in wat meer detail waar die helpers voor ingezet kunnen worden of wat voor soort helpers erin staan, of haal het weg (tenzij het echt per se nodig is dat alle code van commentaar voorzien wordt).

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/Customers/Services/UsersService.cs
> +            // }
Als deze code weg moet, dan ook graag echt weghalen en niet alleen in commentaar zetten.

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/Dashboard/Models/ServiceLog.cs
> +/// This class describes an object that keeps an log of an service
Grammaticafoutje hier: Het is niet `an log`, maar `a log`, en `an service` moet `a service` zijn.

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/DigitalOcean/Interfaces/IDigitalOceanService.cs
> +        /// Processes a call back from Digital Ocean's OAUTH2 authentication.
Callback is één woord, dus `call back` moet gewoon `callback` zijn.

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/DigitalOcean/Models/DatabaseConnectionApiModel.cs
> +    /// This class describes an object that makes an connection to the database via an API
Grammaticafoutje hier: Het is niet `an connection`, maar `a connection`.

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/DigitalOcean/Models/DatabaseConnectionApiModel.cs
> +        /// SSL that can used for logging in
Ik denk dat hier `can be used` moest staan i.p.v. `can used`.

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/DigitalOcean/Models/GetDatabaseResponseModel.cs
> +    /// Class that describes an object which has an response from an database
Grammaticafoutje hier: Het is niet `an response`, maar `a response`, en `an database` moet `a database` zijn.

2022-11-18 08:32 UTC, HansJuice commented on Api/Modules/Templates/Services/TemplatesService.cs
> +            // }
Als deze code weg moet, dan ook graag echt weghalen en niet alleen in commentaar zetten.

2022-12-22 12:59 UTC, JeremyMullerr commented
Ik heb de feedback verwerkt en dit gecommit

2022-12-23 09:35 UTC, HansJuice commented
Er is een merge conflict ontstaan die eerst opgelost moet worden. Waarschijnlijk moet je alle wijzigingen van develop een keer mergen naar deze branch.

2022-12-30 08:17 UTC, HansJuice approved these changes

2022-12-30 08:17 UTC, merged