Updated kendo common material css version / fixed styling issues on d…
happy-geeks/wiser pull request #200
Opened 2022-12-21 11:04 UTC by RobMeulenbroeks

Updated kendo common material css version / fixed styling issues on dashboard windows

2022-12-22 15:37 UTC, GilianJuice requested changes

2022-12-22 15:37 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Css/Dashboard.scss
> +    //position: relative;
Graag geen code in commentaar laten staan.

2022-12-22 15:37 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Css/Dashboard.scss
> +    flex-direction: column;
Waarom heb je hier een spatie toegevoegd aan het einde? Graag weghalen.

2022-12-22 15:37 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Css/Dashboard.scss
> +                //align-items: center;
Geen code in commentaar laten staan.

2022-12-22 15:37 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Css/Dashboard.scss
> +        } */
Geen code in commentaar laten staan.

2022-12-22 15:37 UTC, GilianJuice commented on FrontEnd/Modules/Dashboard/Css/Dashboard.scss
> +
Onnodige spaties/tabs toegevoegd.

2022-12-22 15:38 UTC, GilianJuice commented
@RobMeulenbroeks Kun je jezelf inplannen om mijn feedback te verwerken? En graag ook altijd de URL naar Asana in de omschrijving van de pull request zetten (en dan echt alleen de URL, niet de naam van het ticket, zodat mensen niet kunnen zien om welke klant het gaat als ze geen toegang hebben tot Asana).

2022-12-23 13:39 UTC, RobMeulenbroeks commented on FrontEnd/Modules/Dashboard/Css/Dashboard.scss
> +
Deze tab/spaties zie ik niet terug in mijn code.

2022-12-23 14:19 UTC, GilianJuice approved these changes

2022-12-27 12:14 UTC, merged