Added check on reserved values in Javascript
happy-geeks/wiser pull request #206
Opened 2022-12-29 13:15 UTC by JeremyMullerr

Adding a check for reserved Javascript values and throwing an exception if `fieldName` matches a reserved value.
Asana link: https://app.asana.com/0/1201027711166952/1203330222343490

2023-01-03 16:40 UTC, GilianJuice requested changes

2023-01-03 16:40 UTC, GilianJuice commented on Api/Modules/Grids/Services/GridsService.cs
> +                    string[] reservedWordsArray = { "abstract","arguments","await","boolean","break","byte","case","catch","char","class","const","continue","debugger","default","delete","do","double
Graag `var` gebruiken zoals we ook op alle andere plekken doen, zodat het consistent is.

2023-01-03 16:40 UTC, GilianJuice commented on Api/Modules/Grids/Services/GridsService.cs
> +                                throw new Exception( fieldName + " (variable: fieldName) is a reserved Javascript keyword");
Graag string interpolation gebruiken ipv concattenation en de onnodige spatie tussen `(` en `fieldName` weghalen..

2023-01-12 13:24 UTC, JeremyMullerr commented
Wijzigingen gedaan die verwacht zijn.

2023-01-12 13:34 UTC, GilianJuice approved these changes

2023-01-12 13:34 UTC, merged