Increased efficiency and speed of webpack compilation
happy-geeks/wiser pull request #209
Opened 2022-12-30 16:06 UTC by GilianJuice

This is done by splitting vendor scripts into separate chunks, so that they are no longer included in each module. This also makes loading scripts in modules faster and more efficient.

Asana ticket: https://app.asana.com/0/1201027711166952/1203325592628572

2023-01-04 07:45 UTC, MarkVanDijkHG requested changes
Paar kleine dingen even controleren.

2023-01-04 07:45 UTC, MarkVanDijkHG commented on FrontEnd/Core/Scripts/main.js
> +console.log("main.js loaded");
Console log mag weg.

2023-01-04 07:45 UTC, MarkVanDijkHG commented on FrontEnd/Core/Scripts/main.js
> +        switch (event.data.action) {
Aangezien er maar 1 case in de switch statement zit, kan dit niet beter een if statement worden?

2023-01-04 07:45 UTC, MarkVanDijkHG commented on FrontEnd/Core/Scripts/main.js
> +console.log("initiating main class");
Console log mag weg.

2023-01-05 13:19 UTC, GilianJuice commented on FrontEnd/Core/Scripts/main.js
> +console.log("main.js loaded");
Weggehaald.

2023-01-05 13:19 UTC, GilianJuice commented on FrontEnd/Core/Scripts/main.js
> +        switch (event.data.action) {
Weggehaald.

2023-01-05 13:20 UTC, GilianJuice commented on FrontEnd/Core/Scripts/main.js
> +console.log("initiating main class");
Weggehaald.

2023-01-06 07:05 UTC, MarkVanDijkHG approved these changes

2023-01-06 08:26 UTC, merged