Show admin username in history
happy-geeks/wiser pull request #214
Opened 2023-01-03 10:38 UTC by GilianJuice

When the admin user makes changes in Wiser, it would always show the username in history of the user they selected during login. This is changes so that it will now always show their admin username in history.

Also changed username in scripts where it would use "Happy Horizon ([username])", but Happy Horizon is not applicable for external users that use Wiser.

Asana ticket: https://app.asana.com/0/1201027711166952/1203205263979130

2023-01-04 08:09 UTC, MarkVanDijkHG requested changes
Graag de twee punten controleren, één komt op 13 plaatsen voor.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/Admin.js
>              this.settings.happyEmployeeLoggedIn = user.juiceEmployeeName;
Indien mogelijk graag namen aanpassen om referenties naar Happy en Juice eruit te halen.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/Admin.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Communication/Scripts/Index.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Communication/Scripts/Settings.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/ImportExport/Scripts/Export.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/ImportExport/Scripts/Import.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/TaskAlerts/Scripts/TaskAlerts.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/TaskAlerts/Scripts/TaskHistory.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-04 08:09 UTC, MarkVanDijkHG commented on FrontEnd/Modules/VersionControl/Scripts/VersionControl.js
> +            this.settings.username = user.adminAccountName ? user.adminAccountName : user.name;
Momenteel is er geen visueel verschil tussen een admin en normaal account. Zeker als een admin en een normale gebruiker dezelfde naam hebben is het niet te zien wie het heeft gedaan.
Mogelijk iets als: `${user.adminAccountName} (Admin)`
Hierdoor is er nog wel onderscheid.

2023-01-05 13:11 UTC, GilianJuice commented
Ik heb alle opmerkingen verwerkt en ook in de back-end gemaakt dat daar ` (Admin)` wordt toegevoegd aan de gebruikersnaam, wanneer iemand admin is.

2023-01-06 07:03 UTC, MarkVanDijkHG approved these changes

2023-01-06 08:19 UTC, merged