sql createtabels & insertData
happy-geeks/wiser pull request #215
Opened 2023-01-05 09:14 UTC by TvantHooft

Added Overview_fieldtype by CreateTables.sql and By InsertInitialData.sql added ID and value

2023-01-06 08:26 UTC, GilianJuice requested changes
De kolom `overview_fieldtype` wordt niet gebruikt, deze moet daarom niet toegevoegd worden. Ik heb wel 1 query gevonden in Wiser waar die nog gebruikt werd, mogelijk heb je die daarom toegevoegd, maar die query klopte niet en ik heb deze kolom nu uit die query gehaald in de `develop` branch.

Waarom heb je overal ID's toegevoegd aan `InsertInitialData.sql`? Wat is het nut daarvan? Die ID's hebben gewoon auto increment, dus die worden automatisch gevuld.

2023-01-25 07:37 UTC, TvantHooft commented
Ik heb overal Id toegevoegd Omdat die anders de query wou draaien in Navicat. want ik heb het uiteindelijk handmatig moeten toevoegen.

2023-01-25 12:47 UTC, GilianJuice commented
> Ik heb overal Id toegevoegd Omdat die anders de query wou draaien in Navicat. want ik heb het uiteindelijk handmatig moeten toevoegen.

Dat begrijp ik niet helemaal, wat bedoel je daarmee? Wie gaat de query draaien in Navicat en waarom? En wat heeft het toevoegen van ID's te maken met het draaien van de query in Navicat?
Wiser doet niets met Navicat, de code in Wiser mag niet aangepast worden op iets wat nodig zou zijn voor Navicat. Daarnaast werken de originele queries wel gewoon in Navicat.

2023-01-25 13:20 UTC, TvantHooft commented
Toen ik wiser lokaal ging opzetten en ik de database ging maken en dit draaide werd er een halve database aangemaakt. waardoor ik delen zelf als query's moest uitvoeren. om dit te doen stond er dat ik id moest mee geven dus dat heb ik gedaan.

2023-01-25 13:22 UTC, GilianJuice commented
Sorry, maar dan ga ik deze PR sluiten. Als er stond dat je een ID mee moest geven dan kwam dat hoogst waarschijnlijk doordat die kolom niet gemarkeerd was als `auto increment`, dan is deze aanpassing die je hebt gedaan niet de juiste oplossing.

2023-01-25 13:22 UTC, closed without merging