Improvements to the linked-item field
happy-geeks/wiser pull request #241
Opened 2023-03-06 11:11 UTC by GilianJuice

* Variables that don't have a value will now be removed from the text.
* This field now also works with link types that use parent_item_id from wiser_item instead of wiser_itemlink.
* Refactored code to make it better.

Asana ticket: https://app.asana.com/0/1201027711166952/1203789612265932

2023-03-07 13:02 UTC, MarkVanDijkHG requested changes
Paar kleine verbeteringen benodigd.

2023-03-07 13:02 UTC, MarkVanDijkHG commented on Api/Modules/Items/FieldTemplates/linked-item.js
> +            $("<a class='openWindow' href='#' />").html(newValue + "&nbsp;<span class='k-icon k-i-hyperlink-open-sm'></span>").appendTo(field).click((event) => {
Graag de string interpolation weer terug zetten.

2023-03-07 13:02 UTC, MarkVanDijkHG commented on Api/Modules/Items/FieldTemplates/linked-item.js
> +            const regExp = new RegExp("{" + detail.key + "}", "gi");
Graag string interpolation gebruiken.

2023-03-08 09:02 UTC, HansJuice commented
Ik zag dit punt langskomen, en ik vraag me af of we nu niet dubbel werk aan het doen zijn. Ik heb namelijk ook al het e.e.a. aangepast wat al goedgekeurd is voor dit punt: https://app.asana.com/0/1201027711166952/1203351288497689. De pull request van dat punt was deze: https://github.com/happy-geeks/wiser/pull/238

2023-03-08 10:01 UTC, GilianJuice commented
@HansJuice We hebben inderdaad dubbel werk zitten doen. Ik was alweer vergeten dat ik die PR van jou had nagekeken en blijkbaar had ik dan geen pull gedaan bij mij, want jouw aanpassingen had ik bij mij niet toen ik aan dit punt werkten. Ik sluit deze PR en verwijder mijn branch, want dat heeft geen toegevoegde waarde op wat jij al had gedaan.

2023-03-08 10:01 UTC, closed without merging