Added file manager module
happy-geeks/wiser pull request #242
Opened 2023-03-06 15:06 UTC by GilianJuice

Created a new module for managing files in Wiser.

Asana ticket: https://app.asana.com/0/1201027711166952/1203552019486775

2023-03-08 09:40 UTC, HansJuice commented
Gestart met reviewen, maar nog niet klaar. Het punt is nogal groot.

2023-03-15 09:01 UTC, HansJuice requested changes
Heb een aantal kleine issues in de scripts gevonden. Graag deze oplossen.

2023-03-15 09:28 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +     * @param skipUpdate
Commentaar toegevoegd.

2023-03-15 09:28 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +     * @param {number} moduleId Optional: The id of the module in which the item should be created.
Volgorde parameters nu goed gezet.

2023-03-15 09:28 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +        console.warn("deleteItem in dynamicItems.js called");
Logging weggehaald.

2023-03-15 09:28 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +     * Marks an item as deleted.
Commentaar aangepast zodat die klopt met wat de functie doet.

2023-03-15 09:37 UTC, HansJuice approved these changes

2023-03-15 09:37 UTC, merged