Several improvements to the FileManager module
happy-geeks/wiser pull request #252
Opened 2023-04-18 10:03 UTC by GilianJuice

* Added link to copy the URL of an image or other file to clipboard.
* Added tabstrip so that you can easily switch between the different file managers.
* Refactored the back-end code to properly use controllers and services. 

Asana ticket: https://app.asana.com/0/1201027711166952/1204336876526213

2023-04-19 08:24 UTC, HansJuice requested changes

2023-04-19 08:24 UTC, HansJuice commented on Api/Modules/Files/Services/Repository/FilesRepository.cs
De indentation in dit bestand lijkt niet consistent te zijn. Soms zijn het tabs en soms spaties. Graag consistent maken.

2023-04-20 07:32 UTC, GilianJuice commented on Api/Modules/Files/Services/Repository/FilesRepository.cs
Huh, geen idee hoe dat is gebeurd, maar ik heb het aangepast zodat het allemaal spaties zijn.

2023-04-20 07:36 UTC, HansJuice approved these changes

2023-04-20 07:36 UTC, merged