Feature/selenium tests
happy-geeks/wiser pull request #258
Opened 2023-04-28 12:32 UTC by MarkVanDijkHG

Add Selenium tests to check specific actions in Wiser 3:

- Login/logout
- Search in Wiser
- Open Wiser item
- Use data selector
- Use grid
- Create, edit and delete Wiser item

https://app.asana.com/0/1201027711166952/1203121535064828

2023-05-03 07:45 UTC, HansJuice requested changes

2023-05-03 07:45 UTC, HansJuice commented on Wiser.Tests/Selenium/Tests.cs
> +            Assert.That(driver.FindElement(By.ClassName("sub-title")).Text, Is.EqualTo("TestMark"));
Graag `"TestMark"` dynamisch maken.

2023-05-03 07:45 UTC, HansJuice commented on Wiser.Tests/Selenium/Tests.cs
> +            Assert.That(driver.FindElement(By.ClassName("sub-title")).Text, Is.EqualTo("TestMark"));
Graag `"TestMark"` dynamisch maken.

2023-05-03 07:45 UTC, HansJuice commented on Wiser.Tests/Selenium/Tests.cs
> +            driver.FindElement(By.CssSelector("#loginForm input")).SendKeys("TestMark");
Graag `"TestMark"` dynamisch maken.

2023-05-03 07:45 UTC, HansJuice commented on Wiser.Tests/Selenium/Tests.cs
> +            Assert.That(driver.FindElement(By.ClassName("sub-title")).Text, Is.EqualTo("TestMark"));
Graag `"TestMark"` dynamisch maken.

2023-05-03 07:45 UTC, HansJuice commented on Wiser.Tests/Wiser.Tests.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Graag project naar .NET 7 omzetten, aangezien Wiser zelf ook .NET 7 is.

2023-05-08 14:09 UTC, MarkVanDijkHG commented on Wiser.Tests/Selenium/Tests.cs
> +            driver.FindElement(By.CssSelector("#loginForm input")).SendKeys("TestMark");
Waarde is dynamisch gemaakt.

2023-05-08 14:09 UTC, MarkVanDijkHG commented on Wiser.Tests/Wiser.Tests.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Project en bijbehorende dependencies zijn geupdate naar .net 7.

2023-05-10 08:00 UTC, HansJuice approved these changes

2023-05-10 08:00 UTC, merged