Feature/create branch dataselector
happy-geeks/wiser pull request #270
Opened 2023-05-19 07:26 UTC by MarkVanDijkHG

Add option to save a data selector to be used to determine what items need to be copied to the new branch.

Depends on changes in the WTS: https://github.com/happy-geeks/wiser-task-scheduler/pull/81

https://app.asana.com/0/1201027711166952/1203918305457021

2023-05-25 12:12 UTC, GilianJuice requested changes

2023-05-25 12:12 UTC, GilianJuice commented on FrontEnd/Core/Scripts/store/index.js
> +            console.log(state);
Deze console.log graag weghalen.

2023-05-26 11:50 UTC, MarkVanDijkHG commented on FrontEnd/Core/Scripts/store/index.js
> +            console.log(state);
COnsole log has been removed.

2023-05-26 11:56 UTC, GilianJuice approved these changes

2023-05-26 11:56 UTC, merged