Feature/import excel file
happy-geeks/wiser pull request #271
Opened 2023-05-26 11:39 UTC by MarkVanDijkHG

Add the option to import Excel files with the Wiser 3 import module.

https://app.asana.com/0/1201027711166952/1199686010158649

2023-05-31 08:32 UTC, HansJuice commented on Api/Modules/Imports/Services/ImportsService.cs
> +
Please remove unnecessary empty lines at the end of functions.

2023-05-31 08:35 UTC, HansJuice commented on Api/Modules/Imports/Services/ImportsService.cs
> +        private (ServiceResult<ImportResultModel> result, int idIndex) CheckHeader(string[] headerFields, ImportResultModel importResult)
Please add comments to describe the method.

2023-05-31 08:35 UTC, HansJuice commented on Api/Modules/Imports/Services/ImportsService.cs
> +        private async Task ReadLineAsync(ImportResultModel importResult,
Please add comments to describe the method.

2023-05-31 08:47 UTC, HansJuice requested changes
Please address the issues listed above.

2023-06-05 06:47 UTC, MarkVanDijkHG commented on Api/Modules/Imports/Services/ImportsService.cs
> +
Line has been removed.

2023-06-05 06:47 UTC, MarkVanDijkHG commented on Api/Modules/Imports/Services/ImportsService.cs
> +        private (ServiceResult<ImportResultModel> result, int idIndex) CheckHeader(string[] headerFields, ImportResultModel importResult)
Summary has been added.

2023-06-05 06:48 UTC, MarkVanDijkHG commented on Api/Modules/Imports/Services/ImportsService.cs
> +        private async Task ReadLineAsync(ImportResultModel importResult,
Summary has been added. Also the name of the method has been improved to better reflect its contents. Instead of ReadLineAsync it is now called ProcessLineAsync since it does more than just reading the line.

2023-06-07 10:29 UTC, merged