template caching option selection
happy-geeks/wiser pull request #272
Opened 2023-05-26 19:28 UTC by MKet

https://app.asana.com/0/1201027711166952/1204618135526175/f

Replace the combobox used to decide the cachingmode with a series of checkboxes so the components of the url can be selected independently of each other.

2023-05-30 10:22 UTC, MarkVanDijkHG requested changes
On multiple places please fix the tupo of "geselecteert" to "geselecteerd".

2023-05-30 10:22 UTC, MarkVanDijkHG commented on Api/Modules/Modules/Services/ModulesService.cs
> +            if (!lastTableUpdates.TryGetValue(TemplateCachingName, out var updateDate) || updateDate < new DateTime(2023, 5, 26))
Date needs to be changed to the date when Wiser with this change is deployed to live.

2023-05-30 10:24 UTC, MarkVanDijkHG commented
As discussed this commit will be merged with the next version of Wiser 3 goes live to time the changes. https://github.com/happy-geeks/geeks-core-library/pull/380

2023-06-01 12:26 UTC, GilianJuice approved these changes

2023-06-01 12:27 UTC, merged