Several improvements for the admin module
happy-geeks/wiser pull request #280
Opened 2023-06-22 12:07 UTC by GilianJuice

* It's now possible to move entity properties to a different tab.
* It's now possible to move entire tabs (with all it's properties) to a different position.
* Fixed problem that a lot of empty properties were saved in options in wiser_entityproperty.
* Fixed error that sometimes occurred when loading a field. Some Wiser instances apparently don't have the column "link_type" of "wiser_entityproperty" set to NOT NULL.
* Fixed problem that moving properties to a different position did not work correctly and cause duplicate order numbers. Also refactored the code.
* Added check to warn the user if they have unsaved changes when they're about to leave the page. This only works for the first tab at the moment.
* Added several missing options for combobox fields.
* Fixed javascript error that occurred when loading a combobox field for the first time.

Asana ticket: https://app.asana.com/0/1201027711166952/1201693099409559

2023-07-04 12:46 UTC, MarkVanDijkHG requested changes
2 small changes.

2023-07-04 12:46 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +        console.log("property", property);
Please remove the console log.

2023-07-04 12:46 UTC, MarkVanDijkHG commented on Api/Modules/EntityProperties/Services/EntityPropertiesService.cs
> +
Please remove the second new line.

2023-07-12 11:28 UTC, GilianJuice commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +        console.log("property", property);
I removed the console.log

2023-07-12 11:29 UTC, GilianJuice commented on Api/Modules/EntityProperties/Services/EntityPropertiesService.cs
> +
I removed the extra new line.

2023-07-12 11:29 UTC, GilianJuice commented
I merged develop into this branch and fixed merge conflicts.

2023-07-12 11:45 UTC, MarkVanDijkHG approved these changes

2023-07-12 11:46 UTC, merged