add styled output api endpoint
happy-geeks/wiser pull request #299
Opened 2023-07-12 13:28 UTC by MikeVanMourik

Asana: https://app.asana.com/0/1200923549887805/1204976361057387/f

the first version of the new styledoutput api, will expect this to be further improved as its rather crude right now but for now this should allow more control over the output of our queries.

2023-07-13 10:30 UTC, GilianJuice commented
Please explain what this is for and what it does exactly. I don't understand what the point of this is and what it does, even after reading through the code and the Asana ticket.

2023-07-13 11:31 UTC, GilianJuice requested changes
I don't agree with making an entire new module for this. Please move all your code to the QueriesModule, that makes a lot more sense in my opinion. I think you don't even need a new controller, interface and service, you could just add your function to the `QueriesController` and `IQueriesService`, since that's what they're meant for.

Also, don't forget to add the new table you made to the functions that automatically update tables in customer databases and in the script for creating new customers/databases.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Controllers/StyledOutputController.cs
> +        /// <param name="stripNewlines">replaces \r\n \n and \t when encountered in the format.</param>
The parameter is called `stripNewLines`, but in this comment you say that you also strip `\t`, which is a tab and not a newline. Is this a mistake in the comment? Otherwise you should rename this parameter to `stripNewlinesAndTabs` or maybe just `stripWhiteSpace`.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Interfaces/IStyledOutputService.cs
> +        /// <param name="stripNewlines">replaces \r\n \n and \t when encountered in the format.</param>
Same here, either change the parameter name so that it does what it says what it does, or fix the comment.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Interfaces/IStyledOutputService.cs
> +}
Here too, you created a new service for doing something with queries. In my eyes it makes much more sense to add the `GetStyledOutputResultJsonAsync` to the `IQueriesService` interface.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Models/StyledOutputModel.cs
> +}
Please use PascalCase instead of Snake_case, like the rest of Wiser does.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +            var formatQuery =  $"SELECT query_id, format_begin, format_item, format_end, return_type FROM wiser_styled_output WHERE id = ?id";
Please create a constant for the table `wiser_styled_output` and add that to the GCL, in the class `WiserTableNames`, like we do for all other table names.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +            dataTable = await clientDatabaseConnection.GetAsync(query);
Please use `IQueriesService.GetAsync(id)` to get the query, so that we don't have duplicate code.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +        }
Don't create your own replacement function. Use One of the overloads of `IStringReplacementsService.DoReplacements()` from the GCL. It already has an overload that uses `JToken`, which also works with `JObject`.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +                var startIndex = itemValue.IndexOf("{StyledOutput",index);
Please add a space after the comma.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +                var endIndex = itemValue.IndexOf("}",startIndex) + 1;
Please add a space after the comma.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +                index = startIndex+1;
Please add spaces around the `+` character.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +                var sections = styleString.Substring(1,styleString.Length-2).Split('~');
Please add spaces after the commas and around the `-` character.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +                var styleString = itemValue.Substring(startIndex, endIndex - startIndex );
Please remove the space between `startIndex` and `);`.

2023-07-13 11:31 UTC, GilianJuice commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +                    // mvm_note: skip 0,1 and move per 2
Can you extend this comment to also explain why you skip 0 and 1 and why you move per 2 instead of 1? And what does "mvm_note" mean?

2023-07-13 14:50 UTC, MikeVanMourik commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +            var formatQuery =  $"SELECT query_id, format_begin, format_item, format_end, return_type FROM wiser_styled_output WHERE id = ?id";
https://github.com/happy-geeks/geeks-core-library/pull/412
pull request made ande changed added to remove todo

2023-07-13 15:37 UTC, MikeVanMourik commented on Api/Modules/StyledOutput/Services/StyledOutputService.cs
> +        }
replaced

2023-07-14 13:35 UTC, GilianJuice requested changes

2023-07-14 13:35 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            clientDatabaseConnection.AddParameter("id", formatQueryId);
This line is not needed anymore I believe, please remove it (unless I'm wrong).

2023-07-14 13:35 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    List<KeyValuePair<string, object>> subParameters = parameters;
Sorry, I didn't notice this last time, but why do you create a new variable here? A `List` is a reference type, so `subParameters` will just contain a reference to `parameters` and any changes made to `subParameters` will also be done to `parameters`. So to avoid confusion, it would be better to just use `parameters` everywhere. Or if you intended to make a copy of `parameters`, you should do something like this instead:
```
var subParameters = new List<KeyValuePair<string, object>>();
subParameters.AddRange(parameters);
```

Also, we always use `var` instead of specifying the type, because you can easily see what the type of a variable is by inspecting it.

2023-07-14 13:43 UTC, GilianJuice commented
You also didn't do anything with my second comment yet, please look at that and ask me or Mark if you have questions about that:
> Also, don't forget to add the new table you made to the functions that automatically update tables in customer databases and in the script for creating new customers/databases.

2023-07-18 07:26 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            clientDatabaseConnection.AddParameter("id", formatQueryId);
removed it and tested it, you were correct this one was no longer needed

2023-07-18 07:33 UTC, MikeVanMourik commented
Damn, Sorry was so cooked by the end of that day that i missed your comment, ofcourse the new table design should be included. ill hook that up right now

2023-07-18 08:09 UTC, MikeVanMourik commented
fixed made, and new pr made for further gcl changes:
https://github.com/happy-geeks/geeks-core-library/pull/417

2023-07-18 08:10 UTC, GilianJuice approved these changes

2023-07-18 08:10 UTC, merged