add detection for cyclic loops inside styled output feature
happy-geeks/wiser pull request #313
Opened 2023-08-01 14:24 UTC by MikeVanMourik

asana: https://app.asana.com/0/1201027711166952/1205169244716095/f
Add cyclic loop detection to styled output

2023-08-03 10:33 UTC, GilianJuice requested changes

2023-08-03 10:33 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +using DocumentFormat.OpenXml.Office2010.Excel;
Please remove this using. Your code has nothing to do with Excel as far as I know?

2023-08-03 10:33 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            var usedIds = inUseStyleIds == null ? new List<int>() : new List<int>(inUseStyleIds);
This line can be made much shorter like this:
```c#
inUseStyleIds ??= new List<int>();
```
Why do you create a new variable here anyway and what is the `new List<int>(inUseStyleIds)` for?

2023-08-03 11:18 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +using DocumentFormat.OpenXml.Office2010.Excel;
you are right, not sure why that got added.. ill remove it

2023-08-03 11:25 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            var usedIds = inUseStyleIds == null ? new List<int>() : new List<int>(inUseStyleIds);
I need that copy so it resets

2023-08-10 11:59 UTC, GilianJuice approved these changes

2023-08-10 11:59 UTC, merged