add optional resultsPerPage parameter to styledOutputService
happy-geeks/wiser pull request #324
Opened 2023-08-11 13:41 UTC by MikeVanMourik

add optional resultsPerPage parameter to styledOutputService
Asana: none, just good to have

2023-08-15 06:42 UTC, MarkVanDijkHG requested changes
In multiple methods the parameter "resultsPerPage" is set to have a default of 0 if not filled. Later on in the code it is set to a default value if the provided value was 0. Isn't it more logical to set the default value in the methods to the default value used later on? Then it is directly clear what the default is and won't cause confusion because the endpoint makes it look like that if no value is provided you won't get any result.

2023-08-15 06:42 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            pageResultCount = pageResultCount > maxResultsPerPage ? maxResultsPerPage : pageResultCount;
Isn't it more readable to use the Math.Min function here?

2023-08-18 07:18 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            pageResultCount = pageResultCount > maxResultsPerPage ? maxResultsPerPage : pageResultCount;
im just in love with the short hand if statement, its been swapped out :)

2023-08-18 07:20 UTC, MikeVanMourik commented
tried to keep all the settings in the same class, but that makes no sense ofcourse since the controller is the part that is exposed to the user anyway, i changed things around to make the pagecount no longer optional in the classes and filled in the default value in the controller

2023-08-18 07:20 UTC, MikeVanMourik commented
also noticed 2 files were included that were not in use, removed those as well

2023-08-18 10:00 UTC, MarkVanDijkHG approved these changes

2023-08-18 10:00 UTC, merged