add raw element support to the styled output module for sub styles
happy-geeks/wiser pull request #335
Opened 2023-08-30 15:01 UTC by MikeVanMourik

2023-08-30 15:03 UTC, MikeVanMourik commented
asana: https://app.asana.com/0/0/1205277251974264/f

2023-09-07 15:06 UTC, GilianJuice requested changes

2023-09-07 15:06 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            if (response.StatusCode == HttpStatusCode.OK)
Please reverse these if statements, it makes the code more readable. Like this:
```C#
if (response.StatusCode != HttpStatusCode.OK)
{
	return new ServiceResult<JToken>
	{
		StatusCode = response.StatusCode,
		ErrorMessage = response.ErrorMessage
	};
}

if (response.ModelObject.Length == 0)
{
	return new ServiceResult<JToken>
	{
		StatusCode = HttpStatusCode.OK,
		ModelObject = ""
	};
}

try
{
	return new ServiceResult<JToken>
	{
		StatusCode = HttpStatusCode.OK,
		ModelObject = JToken.Parse(response.ModelObject)
	};
}
catch (Exception e)
{
	return new ServiceResult<JToken>
	{
		StatusCode = HttpStatusCode.InternalServerError,
		ErrorMessage = $"Wiser styledoutput with ID '{id}' could not convert to Json with exception: '{e.ToString()}'"
	};
}
```

This way, the actual functional code doesn't need to be indented so far to the right, if you have multiple if statements in a row and this way you don't need to scroll down so far if you want to see what happens if an error occurs, because error handling is normally a lot less code that the actual code that happens if all the checks pass. This makes the code more easily readable and better maintainable.

Also, please add logging. You should always log all exceptions that occur. You only return the exception to the user now, but you don't log it to the logs of Wiser. Use `ILogger` for that.

2023-09-08 07:32 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            if (response.StatusCode == HttpStatusCode.OK)
changed made, will try to do more early out ifs instead of nested ifs in the future.

logging added as well. 

Cheers

2023-09-08 07:46 UTC, GilianJuice approved these changes

2023-09-08 07:46 UTC, merged