Functionality for loading GCL/Wiser plugins
happy-geeks/wiser pull request #337
Opened 2023-09-04 15:15 UTC by GilianJuice

We have split the GCL into multiple smaller libraries. For example, the configurator is now a separate library and no longer part of the base GCL library. To still be able to use and config configurators in Wiser, we need to be able to load plugins dynamically.

2023-09-12 13:10 UTC, MarkVanDijkHG requested changes

2023-09-12 13:10 UTC, MarkVanDijkHG commented on Api/appsettings.Development.json
> +    "PluginsDirectory": "C:\\Ontwikkeling\\Intern\\Wiser 3\\Api\\Plugins"
Isn't it possible to have a relative path here since it will be inside the project?

2023-09-12 13:10 UTC, MarkVanDijkHG commented on FrontEnd/appsettings.Development.json
> +    "PluginsDirectory": "C:\\Ontwikkeling\\Intern\\Wiser 3\\Api\\Plugins"
Isn't it possible to have a relative path here since it will be inside the project?
If not, the path points to the API directory while it is the appsettings from the front-end.

2023-09-14 13:14 UTC, GilianJuice commented on FrontEnd/appsettings.Development.json
> +    "PluginsDirectory": "C:\\Ontwikkeling\\Intern\\Wiser 3\\Api\\Plugins"
That this is the same directory as the API is on purpose, because the plugins should always be the same in both projects. Then we don't have to add the same plugins in 2 locations.

2023-09-14 13:51 UTC, GilianJuice commented on Api/appsettings.Development.json
> +    "PluginsDirectory": "C:\\Ontwikkeling\\Intern\\Wiser 3\\Api\\Plugins"
I made this possible now, it wasn't before.

2023-09-18 06:10 UTC, MarkVanDijkHG approved these changes

2023-09-18 06:10 UTC, merged