Replaced id input with dropdown box select
happy-geeks/wiser pull request #350
Opened 2023-09-21 11:17 UTC by HappyMaarten

Replaced action button query id input field with dropdown box to select query. Id of selected query is shown in a label.

2023-09-25 06:00 UTC, MarkVanDijkHG requested changes

2023-09-25 06:00 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +                placeholder: "Select een query...",
Please use here the correct Dutch for "Select".

2023-09-25 06:59 UTC, HappyMaarten commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +                    document.getElementById("actionButtonQueryIdLbl").innerHTML = "id: " + (item !== undefined ? item.id : -1);
Fixed

2023-09-25 06:59 UTC, HappyMaarten commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +                placeholder: "Select een query...",
Fixed

2023-09-26 12:28 UTC, MarkVanDijkHG approved these changes

2023-09-26 12:29 UTC, merged