Incorrect error message on property add/delete
happy-geeks/wiser pull request #356
Opened 2023-09-22 13:44 UTC by HappyMaarten

1. The crash happened in selectTabInTreeView which was inside the try-except scope, producing the incorrect add/remove failed error message.
2. Code is trying to open non-existing tabs in the treeview. It should try to open the default tree folder if tabName is empty.
3. Made selectTabInTreeView more defensive because it is possible the provided tab no longer exists (when the last property is deleted for example)

2023-09-25 06:05 UTC, MarkVanDijkHG requested changes

2023-09-25 06:05 UTC, MarkVanDijkHG commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +            console.warn("Unable to open tab " + tabName + " in tree view");
Please use string interpolation instead of concatenation.

2023-09-25 07:44 UTC, HappyMaarten commented on FrontEnd/Modules/Admin/Scripts/EntityTab.js
> +            console.warn("Unable to open tab " + tabName + " in tree view");
Fixed

2023-09-26 12:41 UTC, MarkVanDijkHG approved these changes

2023-09-26 12:41 UTC, merged