Disable updating moduleId in Wiser configuration - add watch command for easier use
happy-geeks/wiser pull request #379
Opened 2023-10-18 14:33 UTC by celineloos1997

Removed possibility of updating the module ID. Also added a watch command reference to the package.json for easier use.

Ticket: https://app.asana.com/0/1201027711166952/1203115791838029/f

Screenshot beneath is changed view; moduleID inputfield has been changed to a label.
![image](https://github.com/happy-geeks/wiser/assets/145993942/0d496f65-46eb-472d-9813-4cceb7966c83)

2023-10-25 13:29 UTC, HansHappyHorizon requested changes

2023-10-25 13:29 UTC, HansHappyHorizon commented on FrontEnd/Modules/Admin/Scripts/ModuleTab.js
> +        if (isNaN(moduleId)) {
Retrieving the module ID by parsing the HTML of an element is a hacky and somewhat messy solution in my opinion. I think there are better ways to do it, like adding a hidden input, or adding a data attribute to the label that holds the module ID. Here's some possible solutions that I came up with:

### Possible solution 1
#### html
```html
<input type="hidden" id="moduleId" />
<label id="moduleIdLabel" class="textField k-input" style="text-indent: 10px;"></label>
```
#### js
```js
// Setting:
document.getElementById("moduleIdLabel").innerHTML = resultSet.id;
document.getElementById("moduleId").value = resultSet.id;

// Retrieving from the hidden input:
const moduleId = Number.parseInt(document.getElementById("moduleId").value);
```

### Possible solution 2
#### js
```js
// Setting:
document.getElementById("moduleId").innerHTML = resultSet.id; // Visual.
document.getElementById("moduleId").dataset.moduleId = resultSet.id; // Data.

// Retrieving from the dataset:
const moduleId = Number.parseInt(document.getElementById("moduleId").dataset.moduleId);
```

2023-10-25 13:29 UTC, HansHappyHorizon commented on FrontEnd/package.json
This change is not related to the issue, so it should be part of a different pull request.

As a side note: It isn't necessary to add the path to the webpack command, so instead of `node_modules\\.bin\\webpack --mode=development -w` it can just be `webpack --mode=development -w`.

2023-10-26 09:47 UTC, GilianJuice commented on FrontEnd/package.json
@HansHappyHorizon Your last comment isn't true. You should always add the path to webpack, to make sure that you use the webpack version that comes with Wiser. If you don't add the path, it will use any webpack version you might have installed. There have been several not backwards compatible changes to webpack in the past, so there is a relatively big chance that you will get an error if you use webpack of a different version.

I specifically added the path of webpack to the README, because we've had these issues in the past. Like some of our other teams, use different versions of webpack by default.

2023-10-26 13:20 UTC, HansHappyHorizon commented on FrontEnd/package.json
I see, I wasn't aware of that. In my experience with Wiser and other projects it worked just fine without specifying the entire path, so I thought people used the entire path because they didn't realize it wasn't necessary. But if there were issues with it in the past and adding the path solves those issues, then my comment about the path can be disregarded.

2023-11-03 16:07 UTC, GilianJuice commented on FrontEnd/package.json
@celineloos1997 We talked about Hans' side note about the full path that can be disregarded, that doesn't mean you can disregard his main comment, that this change has nothing to do with this pull request. Why did you even make this change? You updated webpack, but have you tested everything thoroughly with the new webpack? Because, as we talked about, sometimes new versions of webpack can break things.

2023-11-06 07:58 UTC, GilianJuice approved these changes

2023-11-06 07:59 UTC, merged