Replaced text fields in Template histories with actual diff fields
happy-geeks/wiser pull request #394
Opened 2023-11-03 10:41 UTC by HappyMaarten

Added JS to render Diff2Html fields instead of the big text areas (for HTML, queries, etc) in the Template and Dynamic Content history tabs. Adjusted the way the HTML is generated for those tabs to simplify the JS code.

2023-11-09 13:37 UTC, GilianJuice requested changes

2023-11-09 13:37 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
If you use window.parent, then please always check if it actually exists, because there are cases when it doesn't exist (such as when you open this page in a separate tab, outside of Wiser, which developers sometimes do when testing/debugging something).

2023-11-09 13:37 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
If you use window.parent, then please always check if it actually exists, because there are cases when it doesn't exist (such as when you open this page in a separate tab, outside of Wiser, which developers sometimes do when testing/debugging something).

2023-11-09 13:37 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
Also, your code is a little inefficient. You could also just do this:
```javascript
 window.parent.Templates.createHistoryDiffFields(document.querySelector("#right-pane div.historyContainer"));
````

2023-11-09 13:37 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
Also, your code is a little inefficient. You could also just do this:
```javascript
 window.parent.Templates.createHistoryDiffFields(document.querySelector("#right-pane div.historyContainer"));
````

2023-11-09 13:37 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            const pretty = require('pretty');
Please use double quotes, like the rest of the quote, so that it's consistent. (In javascript there is no difference between using single quotes or double quotes.)

2023-11-09 13:37 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Views/DynamicContent/Partials/HistoryInputGenerator.cshtml
> +@* @model FrontEnd.Modules.Templates.Models.FieldViewModel *@
Please remove this comment, don't leave commented code in commits.

2023-11-09 13:49 UTC, HappyMaarten commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
Added the check, but if it is possible window.parent doesn't exist that means the diff fields won't be generated. There is actually nothing in the createHistoryDiffFields function that needs something from the window.parent.Templates instance. I simply call that one because I didn't want to create a duplicate function in DynamicContent.js. What would be a better location for that function to make sure both locations always have access to it?

2023-11-09 13:50 UTC, HappyMaarten commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
Didn't know about the querySelector syntax, thanks

2023-11-09 13:50 UTC, HappyMaarten commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            const pretty = require('pretty');
Done

2023-11-09 13:50 UTC, HappyMaarten commented on FrontEnd/Modules/Templates/Views/DynamicContent/Partials/HistoryInputGenerator.cshtml
> +@* @model FrontEnd.Modules.Templates.Models.FieldViewModel *@
Oopsie

2023-11-09 15:01 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
The location is fine, we don't have a better one, unless you want to make a new class. It's just that if you open the frame in a new tab, that you don't have to waste time searching for a strange nullreference exception. If you throw a clear error like "The history only works while running in an iframe" or something, then it's immediately clear to the developer that they can't test that functionality in a separate tab/window.

2023-11-09 15:07 UTC, HappyMaarten commented on FrontEnd/Modules/Templates/Scripts/DynamicContent.js
> +                window.parent.Templates.createHistoryDiffFields(document.getElementById("right-pane").querySelector("div.historyContainer"));
Added the error popup in that case

2023-11-10 08:08 UTC, GilianJuice approved these changes

2023-11-10 08:08 UTC, merged