Bugfix gridtooltips
happy-geeks/wiser pull request #395
Opened 2023-11-03 13:44 UTC by HappyMaarten

There was a bug in the code made for https://app.asana.com/0/1201027711166952/1204420385110393
The kendoTooltip function in Templates.js was not available because the kendoTooltip.js was not imported
Also reduced the amount of jQuery to reduce DOM searches

2023-11-08 09:37 UTC, HansHappyHorizon requested changes

2023-11-08 09:37 UTC, HansHappyHorizon commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +            this.servicesGrid = servicesGridElement.kendoGrid({
I don't think this works, because `servicesGridElement` is not a jQuery object here, and the `kendoGrid` function only works on jQuery objects. The same goes for the `kendoTooltip` function calls that are below this line.

2023-11-09 08:36 UTC, HappyMaarten commented on FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
> +            this.servicesGrid = servicesGridElement.kendoGrid({
Oh, I tested the difference between $(servicesGridElement) and simply servicesGridElement and they seemed to be the same. I guess not then.

2023-11-15 08:41 UTC, HansHappyHorizon approved these changes

2023-11-15 08:41 UTC, merged