Feature/kendo update 2023
happy-geeks/wiser pull request #399
Opened 2023-11-08 11:17 UTC by ericarts

Additional styling issues resolved

2023-11-20 11:20 UTC, MikeVanMourik requested changes

2023-11-20 11:20 UTC, MikeVanMourik commented on FrontEnd/appsettings.Development.json
> +    "SecretsBaseDirectory": "\\\\149.210.132.136\\Juice projects\\AppSettings\\WiserCore\\FrontEnd\\"
Don't use static ip, instead of the Z: drive mapping

2023-11-20 11:20 UTC, MikeVanMourik commented on FrontEnd/package.json
> +    "monaco-editor": "^0.39.0",
it this a intentional dependency and needed for the Kendo update? or is it unrelated?

2024-03-11 11:04 UTC, MikeVanMourik commented
whats the status of this? feels like its been stuck for a while? @GilianJuice / @ericarts ?

2024-06-24 06:49 UTC, GilianJuice commented
Closing this because it's too out-dated already. Have to redo this sometime with the latest version of Kendo.

2024-06-24 06:49 UTC, closed without merging