READY -Added feature to drop single or multiple files in the treeview
happy-geeks/wiser pull request #41
Opened 2022-03-24 16:40 UTC by StijnvdH95

The adding of files has been altered into the create template functions and endpoints to prevent duplicat code. The methods will now accept a template editor value as an optional parameter.

2022-03-29 11:30 UTC, GilianJuice requested changes
A.u.b. je code wat netter maken en houden aan onze programmeerrichtlijnen. Zie specifieke berichten die ik bij de code heb geplaatst.

2022-03-29 11:30 UTC, GilianJuice commented on Api/Modules/Templates/Models/Template/NewTemplateModel.cs
> +        public string name { get; set; }
Properties moeten altijd PascalCase zijn, dus `Name` ipv `name` en `Type` ipv `type`. Dit gaat dan nog steeds goed met serializen, in de JSON kan/moet het wel in camelCase zijn, dus de JSON niet aanpassen, alleen dit model in C#.

2022-03-29 11:30 UTC, GilianJuice commented on Api/Modules/Templates/Services/CachedTemplatesService.cs
> +        public async Task<ServiceResult<TemplateTreeViewModel>> CreateAsync(ClaimsIdentity identity, string name, int parent, TemplateTypes type, string editorValue="")
Graag spaties toevoegen: `editorValue=""` --> `editorValue = ""`

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            if (event.originalEvent.dataTransfer.items) {
Graag de if-statement hier omdraaien, zodat het dit wordt:
```javascript
if (!event.originalEvent.dataTransfer.items) {
    return;
}

// Rest van code.
```
Op die manier wordt code overzichtelijker en hoef je minder in te springen naar rechts.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    if (event.originalEvent.dataTransfer.items[i].kind === 'file') {
Graag de if-statement hier omdraaien, zodat het dit wordt:
```javascript
if (event.originalEvent.dataTransfer.items[i].kind !== 'file') {
    continue;
}

// Rest van code.
```
Op die manier wordt code overzichtelijker en hoef je minder in te springen naar rechts.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    if (event.originalEvent.dataTransfer.items[i].kind === 'file') {
Graag ook overal dubbel quotes gebruiken, zodat het consistent is met de rest.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                        var file = event.originalEvent.dataTransfer.items[i].getAsFile();
Graag nooit `var` gebruiken, altijd `const` (als de waarde niet meer aangepast gaat worden) of `let` (als de waarde later nog wel aangepast wordt).

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                        reader.onload = (function (file) {
Graag arrow functions gebruiken, dus `(file) => {` ipv `function (file) {`.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                                filename.join('.');
Deze regel code is nutteloos, graag controleren waarom die hier staat en weghalen als die niet nodig is, of anders iets mee doen. De `join()` functie geeft een string terug als resultaat, als je daar niets mee doet, dan heeft die code geen zin.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                            return async function (event) {
Hier ook arrow function gebruiken.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            $(".window-content #left-pane div.k-content").on("dragover", function (e) {
Graag arrow function gebruiken en geen afkortingen. Dus `(event) => {` ipv `function(e) {`.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                e = e || event;
Deze regel is nutteloos, graag weghalen.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            console.log("Binding drop event");
Console.log weghalen.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    data: JSON.stringify({ name: encodeURIComponent(title), type: type, editorvalue: body })
Graag hier `encodeURIComponent` weghalen, dat moet je allen gebruiken voor waardes in de querystring, niet in JSON.

2022-03-29 11:30 UTC, GilianJuice commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +        async createNewTemplate(parentId, title, type, treeView, parentElement, body='') {
Graag spaties toevoegen en dubbele quotes gebruiken, dus `body = ""` ipv `body=''`.

2022-04-08 11:16 UTC, StijnvdH95 commented on Api/Modules/Templates/Models/Template/NewTemplateModel.cs
> +        public string name { get; set; }
Feedback is verwerkt, het model heeft nu properties in PascalCase.

2022-04-08 11:16 UTC, StijnvdH95 commented on Api/Modules/Templates/Services/CachedTemplatesService.cs
> +        public async Task<ServiceResult<TemplateTreeViewModel>> CreateAsync(ClaimsIdentity identity, string name, int parent, TemplateTypes type, string editorValue="")
Feedback toegepast

2022-04-08 11:17 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            if (event.originalEvent.dataTransfer.items) {
Feedback toegepast

2022-04-08 11:18 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    if (event.originalEvent.dataTransfer.items[i].kind === 'file') {
Feedback toegepast, single quotes zijn vervangen door dubbel quotes.

2022-04-08 11:18 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                        var file = event.originalEvent.dataTransfer.items[i].getAsFile();
Const wordt gebruikt, de instanties van var heb ik nu vervangen met let.

2022-04-08 11:19 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            $(".window-content #left-pane div.k-content").on("dragover", function (e) {
Feedback toegepast

2022-04-08 11:19 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                e = e || event;
Deze regel is nu weggehaald

2022-04-08 11:19 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +            console.log("Binding drop event");
Weggehaald

2022-04-08 11:19 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +                    data: JSON.stringify({ name: encodeURIComponent(title), type: type, editorvalue: body })
Weggehaald, dit was nog van een eerder versie blijven hangen.

2022-04-08 11:20 UTC, StijnvdH95 commented on FrontEnd/Modules/Templates/Scripts/Templates.js
> +        async createNewTemplate(parentId, title, type, treeView, parentElement, body='') {
Feedback toegepast

2022-04-12 11:20 UTC, GilianJuice approved these changes

2022-04-12 11:21 UTC, merged