Styling improvements
happy-geeks/wiser pull request #428
Opened 2023-12-08 13:51 UTC by ferryvandegraaf

- minimal window size for popups (50% of screen) - so small popups don't break the title
- better UI for rows in table (more padding and no lines)
- (more) and variable radius of corners for buttons and windows

This styling was tested on various modules and grids and windows and showed improvement everywhere.

2023-12-12 14:08 UTC, GilianJuice requested changes

2023-12-12 14:08 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/kendo.wiser.css
> +	border-bottom-width: 0px!important;
Can you add a screenshot of how this looks, because this seems very strange to me. Why would you remove the border between rows? I think that would not look nice. Also, please don't use `!important` if you can avoid it. In most cases you can just use a more specific class to get what you want, you almost never need `!important`.

2023-12-13 10:30 UTC, ferryvandegraaf commented on FrontEnd/Modules/Base/Css/kendo.wiser.css
> +	border-bottom-width: 0px!important;
Hi Gilian, thank you for your reply. Hereby the screenshot of how this looks. The line is indeed removed but in place is now a alternate background color for each row. The reason i needed to add the !important because it is specific styling from KendoUI which i cannot override another way. These changes were already discussed with Gerke and Eric beforehand (just for your information)

![image](https://github.com/happy-geeks/wiser/assets/15887825/170e6d27-615a-4866-888d-3a29aaa5f59a)

2023-12-13 12:24 UTC, GilianJuice approved these changes

2023-12-13 12:24 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/kendo.wiser.css
> +	border-bottom-width: 0px!important;
Okay thank you for the screenshot and explanation, it looks okay then.

2023-12-13 12:24 UTC, merged