Feature/api call in wiser can now handle csv responses
happy-geeks/wiser pull request #429
Opened 2023-12-08 13:59 UTC by ferryvandegraaf

Calling an API from Wiser (for example with an action-button) did not work for older endpoints that return plain CSV in the return body. Specifically for this return mimetype (text/csv) code is added to handle this type of result. The result is returned in the object with name "content".

Also, the "extraHeaders" property, for example to set the Authorization bearer token can now be added to the API call options, instead adding these headers for each API call.

Example JSON that is now possible in the options of wiser_api_call:
{
	"baseUrl": "https://csvapi.com/api",
	"extraHeaders": {
		"Authorization": "Bearer TOKEN_HERE"
	},
	"contentType" : "text/csv",
	"actions": [
        {
			"function": "/objects/getobjects?type={type}",
			"method": "POST",
			"contentType" : "text/csv",
			"preRequestQueryId": 1,
			"postRequestQueryId": 2
		}
	]
}

This functionality has been tested with a live CSV API from a 3th party and works.

2023-12-12 14:17 UTC, GilianJuice requested changes

2023-12-12 14:17 UTC, GilianJuice commented on FrontEnd/Core/Services/ExternalApisService.cs
> +            if (!header.Key.ToLower().StartsWith(headerPrefix.ToLower()))
Please don't use `ToLower()`. The function `StartsWith` has a second parameter, add `StringComparison.OrdinalIgnoreCase` to that parameter, which does the same thing but better.

2023-12-12 14:17 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +                    if (action.contentType!=="text/csv") {
Please add spaces. It should be like this:
```javascript
if (action.contentType !== "text/csv") {
```

2023-12-12 14:17 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +                        apiResults = {"Content"  : apiResults}
Please remove unnecessary spaces:
```javascript
apiResults = {"Content": apiResults}
```

2023-12-12 14:17 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
> +                    if (action.contentType!=="text/csv") {
Also, this if-statement should be reversed. The way you made it now, it's harder to add more exceptions. If you make the if-statement the other way around, so that the original code is in the `else`, then it's much more logical and easier to later add more else-ifs to this. Or even better, make this into a `switch` statement.

2023-12-27 19:45 UTC, ferryvandegraaf commented on FrontEnd/Core/Services/ExternalApisService.cs
> +            if (!header.Key.ToLower().StartsWith(headerPrefix.ToLower()))
I added a new commit in which this is changed into a switch statement. Please send me a Whatsapp if i need to do something more then just send the commit.

2023-12-27 19:46 UTC, ferryvandegraaf reviewed
This commit was made to resolve the issues by the review

2023-12-27 19:47 UTC, ferryvandegraaf commented
@GilianJuice can you please review again? Let me know by Whatsapp or phone if i did something wrong in the committing of the changes.

2023-12-28 13:18 UTC, GilianJuice approved these changes
Looks good now, thanks.

2023-12-28 13:18 UTC, merged