Feature/load image with itemid and propertyname
happy-geeks/wiser pull request #445
Opened 2023-12-20 09:10 UTC by ferryvandegraaf

Added functionality to load an image from the API with itemId and propertyName instead of fileId

2023-12-21 11:16 UTC, GilianJuice requested changes

2023-12-21 11:16 UTC, GilianJuice commented on Api/Modules/Files/Services/FilesService.cs
> +            if (itemId <= 0)
Please put the code `&& !String.Equals("TEMPORARY_FILE_FROM_WISER", propertyName, StringComparison.OrdinalIgnoreCase)` back, it's still needed. Item IDs are not mandatory for temporary files.

2023-12-21 11:16 UTC, GilianJuice commented on Api/Modules/Items/Services/ItemsService.cs
> +                if (!linkTypeSettings.UseItemParentId)
Why did you add this code? The function `wiserItemsService.CreateAsync` already does this, if you fill the linkType and parentId parameters.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Core/Css/partner/brabantsehoeve.css
Don't add all these partner CSS files, they're not in Git for a reason.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Core/Scss/masterpage.scss
What do these CSS changes have to do with loading images via property name? Please make a separate pull request for this, if this is even needed.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Core/Services/ExternalApisService.cs
I remember seeing these changes in a different pull request, please remove them from this one.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/kendo.custom.css
Please remove these changes from this pull request, they have nothing to do with the description of this PR.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/kendo.wiser.css
Please remove these changes from this pull request, they have nothing to do with the description of this PR.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/variables.css
Please remove these changes from this pull request, they have nothing to do with the description of this PR.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Modules/Base/Scripts/Utils.js
Please remove these changes from this pull request, they have nothing to do with the description of this PR.

2023-12-21 11:16 UTC, GilianJuice commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
Please remove these changes from this pull request, they have nothing to do with the description of this PR.

2023-12-28 08:48 UTC, ferryvandegraaf commented
Sorry Gilian, you are right, by accident i committed other changes in this pull request. Those commits are now reverted.

2023-12-28 13:09 UTC, GilianJuice approved these changes
Thanks for the changes!

2023-12-28 13:09 UTC, merged