Feature/added merg pdfs action
happy-geeks/wiser pull request #461
Opened 2024-01-08 15:08 UTC by ferryvandegraaf

With this new functionality, the 'mergePdf' action can be setup to merge PDF's of different items into one document, directly from Wiser.  This can be used from within a grid (it then uses the encrypted ID in the table, an override query is optional) or as a separate actionbutton (in that case a query is needed).

Setup:
"actions": [
    {
	"type": "mergeFiles",
	"queryId": 1,
	"propertyName":"invoice",
	"fileName": "invoices.pdf"
    }
]

2024-01-11 13:19 UTC, GilianJuice requested changes
This PR contains changes that have already been merged via your other PR https://github.com/happy-geeks/wiser/pull/445. But you explained this before why this is the case. We'll have to try if we can merge this properly, once you fixed the other issues I indicated in my other comments.

2024-01-11 13:19 UTC, GilianJuice commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                            if (queryActionResult.otherData[0].entity_type) action.entityType = queryActionResult.otherData[0].entity_type;
Why did you add 2 times the same if-statement? I think the first statement should check for `fileName` instead of `entity_type`?

2024-01-11 13:19 UTC, GilianJuice commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                                                        ,propertyName:action.propertyName})
Please format this properly (and don't add commas in front of the line, always at the end). Like this:
```javascript
body: JSON.stringify({
    encrypedItemIdsList: encryptedIds,
    entityType: action.entityType || "".
    propertyName: action.propertyName
})
```

2024-01-11 13:19 UTC, GilianJuice commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                        await Misc.downloadFile(pdfResult, action.fileName || "mergedpdf.pdf");
Please add this code to a try/catch block and handle errors properly. If an error occurs now, then the user will see a never ending loader.

2024-01-11 13:19 UTC, GilianJuice commented on Api/Modules/Pdfs/Services/PdfsService.cs
> +            Document mergeResultPdfDocument=null;
Please add proper spacing:
```c#
Document mergeResultPdfDocument = null;
```

2024-01-11 13:19 UTC, GilianJuice commented on Api/Modules/Pdfs/Services/PdfsService.cs
> +                //must PDF be downloaded first?
Don't ask questions in comments, say what is happening. The way your formatted the comment now is very confusing, it sounds like the author of the code isn't sure what it actually does. Also, always add a space after the `//` and always end the sentence with a `.`.

2024-01-11 13:19 UTC, GilianJuice commented on Api/Modules/Pdfs/Services/PdfsService.cs
> +                    mergeResultPdfDocument.AppendDocument(new Document(pdfStream));
Please just add brackets, if/else statements without brackets are very ugly :P and we don't do that anywhere else.

2024-01-27 09:47 UTC, ferryvandegraaf commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                            if (queryActionResult.otherData[0].entity_type) action.entityType = queryActionResult.otherData[0].entity_type;
Resolved in the new commit

2024-01-27 09:47 UTC, ferryvandegraaf commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                                                        ,propertyName:action.propertyName})
Resolved in the new commit

2024-01-27 09:47 UTC, ferryvandegraaf commented on Api/Modules/Pdfs/Services/PdfsService.cs
> +            Document mergeResultPdfDocument=null;
Resolved in the new commit

2024-01-27 09:47 UTC, ferryvandegraaf commented on FrontEnd/Modules/DynamicItems/Scripts/Fields.js
> +                        await Misc.downloadFile(pdfResult, action.fileName || "mergedpdf.pdf");
Resolved in the new commit

2024-01-27 09:47 UTC, ferryvandegraaf commented on Api/Modules/Pdfs/Services/PdfsService.cs
> +                //must PDF be downloaded first?
Resolved in the new commit

2024-01-27 09:47 UTC, ferryvandegraaf commented on Api/Modules/Pdfs/Services/PdfsService.cs
> +                    mergeResultPdfDocument.AppendDocument(new Document(pdfStream));
Resolved in the new commit

2024-01-27 09:49 UTC, ferryvandegraaf commented
I resolved all comments in the new commit also did some bugfixing and added the functionality to have a comma separated list of  propertyNames, so you can merge invoices, offers etc. from one item (customer for example) .

2024-01-29 08:19 UTC, GilianJuice requested changes
Can you change the PropertyNames and EncryptedItemIds properties to be lists? Now you have to convert an array to string in javascript and then convert the string back into an array in C#, that is not very efficient. Just make it an array/list in both places.

2024-01-29 08:19 UTC, GilianJuice commented on Api/Modules/Files/Services/FilesService.cs
> +                query = query.Replace("[wherePart]", "item_id = ?itemId AND property_name = ?propertyName");
Sorry I didn't notice this before, but you forgot to check for itemLinkId. Could you still add this, so that it also works for files on item links?

2024-01-30 14:10 UTC, ferryvandegraaf commented on Api/Modules/Files/Services/FilesService.cs
> +                query = query.Replace("[wherePart]", "item_id = ?itemId AND property_name = ?propertyName");
Hi Gilian, this is changed!

2024-01-30 14:10 UTC, ferryvandegraaf commented
Changed the comma-separated string to a list.
Added functionality to get the file from itemLinks directly by itemLinkId

2024-02-01 08:59 UTC, GilianJuice commented
> Changed the comma-separated string to a list. Added functionality to get the file from itemLinks directly by itemLinkId

You only changed the encryptedIds, not propertyNames. Did you forget this, or was it on purpose?

Also could you write documentation for this new functionality? I'm not sure if you can make pull requests or something for the wiki, otherwise maybe send the text to me via mail and I can add it to the Wiki of Wiser?

2024-03-22 09:47 UTC, ferryvandegraaf commented
Hi GIlian, i changed the string to an array for Propertynames. Can you review? Documentation will follow this weekend.

2024-03-28 09:07 UTC, GilianJuice approved these changes

2024-03-28 09:09 UTC, merged