Also save width and position of column in grids
happy-geeks/wiser pull request #490
Opened 2024-01-27 08:38 UTC by ferryvandegraaf

Before this change only the visibility of columns was saved.

2024-01-31 09:15 UTC, HansHappyHorizon requested changes

2024-01-31 09:15 UTC, HansHappyHorizon commented on FrontEnd/Modules/DynamicItems/Scripts/Grids.js
> +        } catch (error) {}
It's better to at least log the error to give some sort of feedback if something went wrong. Now, if something goes wrong, it can be very hard to tell that an error occurred. You could just add something like this:
```js
console.error("Reading and setting grid settings failed:", error);
```

2024-04-10 12:51 UTC, ferryvandegraaf commented on FrontEnd/Modules/DynamicItems/Scripts/Grids.js
> +        } catch (error) {}
This was changed, please review!

2024-04-11 10:19 UTC, GilianJuice approved these changes
Again, please add proper spacing, otherwise the code is really hard to read. I will add them myself after merging.

2024-04-11 10:19 UTC, merged