Add MaxResultsPerPage settings to StyledOutputService to be configure…
happy-geeks/wiser pull request #491
Opened 2024-01-29 15:30 UTC by MikeVanMourik

asana: https://app.asana.com/0/1200923549887805/1206285916229584/f

2024-01-30 13:28 UTC, MarkVanDijkHG requested changes
Please check your comments to start with a capital letter and end with a period to keep consistent.

2024-01-30 13:28 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            if (apiSettings.MaxResultsPerPage > 0)
If the section "StyledOutput" in de appsettings is not provided. Will this not give a null reference?

2024-01-30 13:28 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private int maxResultsPerPage = 500;
Since this value can now be overriden by a value in the appsettings it might be better to have the default value be set in an or-statement if it can't be retrieved from the appsettings. Or even have it as default value for the "MaxResultsPerPage" property and always set it.

2024-02-01 13:45 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            if (apiSettings.MaxResultsPerPage > 0)
No, checked it, it just returns an empty StyledOutputSetting object which for MaxResultsPerPage has a value of 0, so this does not fail, and also does not set the setting to "0" since i check for that.

2024-02-01 13:52 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private int maxResultsPerPage = 500;
good idea, i changed it to have 500 as the default value, so the if statement was no longer needed.

2024-02-02 07:32 UTC, merged