Add logic for updating parents of sub items through the WTS
happy-geeks/wiser pull request #527
Opened 2024-02-27 15:03 UTC by MikeVanMourik

ASANA: https://app.asana.com/0/1199894242406919/1206544323178367/f

**DONT MERGE WITHOUT CHECKING**
 
This is a second attempt at hooking up "change by/on" logic changed through triggers but with an extra step inbetween to avoid issues with locking/cyclic references in existing costumer code

I also added a initial WTS hookup installation which I think would be usefull also for future (like for example branching setup)

but i need feed back on this, going request @GilianJuice as a reviewer since he is familiar with the previous attempt

2024-03-06 12:35 UTC, GilianJuice requested changes
I have some comments about this:
- Please rename the column `targetId` to `target_id`, so that the styling is consistent with the rest of the columns. Why is this one camel case and the rest snake case?
- You did not create a script for creating the new table `wiser_parent_updates`. Please do that. You need to add this table to `CreateTables.sql` and you also need to add it to the GCL, in `WiserTableNames` and `WiserTableDefinitions`.
- Please fix your indenting in the triggers. All of them are indented too far.
- Please don't use abbreviations. Use `previousItemId` instead of `prevItemId`, for example. Abbreviations are completely unnecessary and make it harder to understand/read the code, they are just lazy. It doesn't matter if a variable name is a little longer, as long as it's easy to read and understand.
- Don't add a WTS configuration for this. This is something that should be done for all tenants, which means this should be hard-coded in the WTS. If we ever want to change this functionality, then we'd have to change all the WTS configurations for all tenants, which is not ideal. The WTS already has a `CleanupService`, for example, which does database cleanup that is the same for all tenants. You should add the handling of `wiser_parent_updates` to a similar service.

2024-03-07 13:25 UTC, MikeVanMourik commented
thank you for the comments / review: 

- Please rename the column targetId to target_id, so that the styling is consistent with the rest of the columns. Why is this one camel case and the rest snake case?

this has been corrected, name uses target_id not sure why i did all others correct but not this one.

- You did not create a script for creating the new table wiser_parent_updates. Please do that. You need to add this table to CreateTables.sql and you also need to add it to the GCL, in WiserTableNames and WiserTableDefinitions.

this was done in a sperate pr https://github.com/happy-geeks/geeks-core-library/pull/526

- Please fix your indenting in the triggers. All of them are indented too far.

done this and then some, we also performed a TAB to Spaces operation and Trim trailing spaces to get this whole file cleaned up in one go

- Please don't use abbreviations. Use previousItemId instead of prevItemId, for example. Abbreviations are completely unnecessary and make it harder to understand/read the code, they are just lazy. It doesn't matter if a variable name is a little longer, as long as it's easy to read and understand.

previous and prev has been silly exception for me, i agree with the fact that they should be full out but prev and next are both 4 letters long which is why i use those normally as it alligns nicely, not needed here though :)

- Don't add a WTS configuration for this. This is something that should be done for all tenants, which means this should be hard-coded in the WTS. If we ever want to change this functionality, then we'd have to change all the WTS configurations for all tenants, which is not ideal. The WTS already has a CleanupService, for example, which does database cleanup that is the same for all tenants. You should add the handling of wiser_parent_updates to a similar service.

this has been promoted to its own service in this pr:

https://github.com/happy-geeks/wiser-task-scheduler/pull/175

2024-03-14 14:04 UTC, GilianJuice requested changes
These changes look good, however I forgot about one thing during my previous check; You only changed the triggers in `CreateTriggers.sql`, but they also need to changed in `CreateDedicatedItemTablesTriggers.sql`. Can you still do this please? Don't forget to save the correct `x_wiser_item` table in those triggers then. Sorry that I didn't mention this before.

2024-03-18 12:15 UTC, GilianJuice approved these changes

2024-03-18 12:16 UTC, merged