Feature/front end wk16
happy-geeks/wiser pull request #56
Opened 2022-05-03 15:28 UTC by HappyYoshy

- Fixed redundant CSS for the full-height tables
- Removed redundant max-height calculation due to flexbox fix
- Fixed an overflow issue on the right panel view. Fixed the height in the right panel view.

2022-05-06 11:56 UTC, GilianJuice requested changes

2022-05-06 11:56 UTC, GilianJuice commented on FrontEnd/Core/Scripts/main.js
> +import { Doc } from "codemirror";
Waarom is dit toegevoegd? Dit lijkt nergens gebruikt te worden. Graag weghalen.

2022-05-06 11:56 UTC, GilianJuice commented on FrontEnd/Core/Scripts/main.js
> +                    }
Waarom is hier whitespace toegevoegd aan het einde van de regel? Graag weghalen.

2022-05-06 11:56 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/masterpage.css
> +/* .k-window-content > .pane-content .k-tabstrip .dynamicTabContent .gridview {
Geen code in commentaar laten staan a.u.b., dat is slordig.

2022-05-06 11:56 UTC, GilianJuice commented on FrontEnd/Modules/Base/Css/masterpage.css
> +/* Removed this styling because it causes flashy content.
Geen code in commentaar laten staan.

2022-05-06 12:30 UTC, HappyYoshy commented on FrontEnd/Core/Scripts/main.js
> +import { Doc } from "codemirror";
@ericarts zou jij naar deze aanpassing willen kijken? Naar mijn weten komt deze nog uit jouw eerdere aanpassingen.

2022-05-09 09:33 UTC, HappyYoshy commented
Fixed merge conflicts

2022-05-10 11:16 UTC, GilianJuice approved these changes

2022-05-10 11:16 UTC, merged