Added support for "ROUTINE" templates
happy-geeks/wiser pull request #58
Opened 2022-05-12 15:21 UTC by HansJuice

These templates are used to create FUNCTION and PROCEDURE routines for MySQL.

2022-05-17 08:46 UTC, GilianJuice requested changes

2022-05-17 08:46 UTC, GilianJuice commented on Api/Modules/Templates/Services/DataLayer/HistoryDataService.cs
> +                    RoutineType = (RoutineTypes)row.Field<int>("return_type"),
Dit lijkt me niet te kloppen, krijg je hier geen foutmelding van? Volgens mij moet dit `(RoutineTypes)row.Field<int>("routine_type")` zijn ipv `(RoutineTypes)row.Field<int>("return_type")`

2022-05-17 10:00 UTC, HansJuice commented on Api/Modules/Templates/Services/DataLayer/HistoryDataService.cs
> +                    RoutineType = (RoutineTypes)row.Field<int>("return_type"),
Dit is aangepast. Daarnaast werkt de historie voor deze properties nu ook echt, in plaats van dat alleen de gegevens werden ingeladen.

2022-05-19 11:35 UTC, GilianJuice approved these changes

2022-05-19 11:37 UTC, merged