add timing logic for styled output
happy-geeks/wiser pull request #614
Opened 2024-06-06 15:29 UTC by MikeVanMourik

# Describe your changes

added timing logging to the styled output service for profiling

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

locally and connecting to the intergamma database

Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation -> i have a seperate asana task for this
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

(there has been a pr for adding the new columns at the geekcorelib, this has been merged already)

# Link to Asana ticket
https://app.asana.com/0/1204371236183532/1206473300071322/f

2024-06-12 09:45 UTC, HansHappyHorizon requested changes
The code itself seems fine, but I've got some nitpicks about the code style as there are some inconsistencies.

2024-06-12 09:45 UTC, HansHappyHorizon commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private Dictionary<int, List<Stopwatch>> timings = new Dictionary<int, List<Stopwatch>>();
Please place one line of white space here so the dictionary variable isn't "sticking" to the summary of the constructor.

2024-06-12 09:45 UTC, HansHappyHorizon commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +		private async Task<ServiceResult<string>> GetStyledOutputResultAsync(ClaimsIdentity identity, string[] allowedFormats, int id, List<KeyValuePair<string, object>> parameters, bool stripNewlinesAndTa
Please update the summary to include a description for the new parameter `callingParent`. And while you're at it, please also fix the ordering of the parameters in the summary (because for some reason the `page` and `resultsPerPage` parameters are reversed).

2024-06-12 09:45 UTC, HansHappyHorizon commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            if ( performanceLogging )
Please remove the spaces inside the parentheses.

2024-06-12 09:45 UTC, HansHappyHorizon commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<ServiceResult<string>> HandleInlineStyleElementsAsync(ClaimsIdentity identity, string itemValue, List<KeyValuePair<string, object>> parameters, bool stripNewlinesAndTabs, i
Please update the summary to include a description for the new parameter `callingParentId`. And while you're at it, please also fix the ordering of the parameters in the summary (because for some reason the `page` and `resultsPerPage` parameters are reversed).

2024-06-24 06:59 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<ServiceResult<string>> HandleInlineStyleElementsAsync(ClaimsIdentity identity, string itemValue, List<KeyValuePair<string, object>> parameters, bool stripNewlinesAndTabs, i
done, no idea why the order of page and resultsper page was swapped

2024-06-24 06:59 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            if ( performanceLogging )
done

2024-06-24 06:59 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +		private async Task<ServiceResult<string>> GetStyledOutputResultAsync(ClaimsIdentity identity, string[] allowedFormats, int id, List<KeyValuePair<string, object>> parameters, bool stripNewlinesAndTa
done, no idea why the order of page and resultsper page was swapped

2024-06-24 06:59 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private Dictionary<int, List<Stopwatch>> timings = new Dictionary<int, List<Stopwatch>>();
done, that s abit ugly indeed

2024-07-09 06:38 UTC, MarkVanDijkHG approved these changes

2024-07-09 06:39 UTC, merged