add caching to styled output service
happy-geeks/wiser pull request #639
Opened 2024-07-16 13:58 UTC by MikeVanMourik

# Describe your changes

Please include a summary of the changes and relevant motivation and context.

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

I ran this locally and ran the main query for one of our costumers
this takes 10 minutes normally, with the cache in it this is 5min

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (not needed)
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

none

# Link to Asana ticket
https://app.asana.com/0/1199894242406919/1207511417583256/f

2024-07-18 11:53 UTC, GilianJuice requested changes
I have a lot of comments, but they're mostly for readability and following our code conventions. However, one change is _very_ important; in some locations you use the `.Result` property on async functions. You should never do this, it's dangerous to use. It causes deadlocks in your code which are very hard to debug. See [this article](https://tooslowexception.com/the-danger-of-asyncawait-and-result-in-one-picture/) for more information. I have added comments to the places where I found them, but please check all your code thoroughly in case I missed any.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
Please also use `ILogger` to log the entire exception. Otherwise it might become very hard to find any problems that occur here in the future. Using `exception.Message` is fine for messages to users, but it's often useless for developers since it doesn't contain the stack trace nor any inner exceptions.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
Same here, please use `ILogger` to log the entire exception, to make debugging easier.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            var query = GetCachedQuery(style.QueryId, identity).Result;
Never use `.Result` on an async functions, that causes deadlocks, memory leaks etc. Please change this to:
```c#
var query = await GetCachedQuery(style.QueryId, identity);
```

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<StyledOutputModel> GetCachedStyle(int id)
Please add the `Async` suffix to the name of this method.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<StyledOutputModel> AddCachedStyle(int id)
Please add the `Async` suffix to the name of this method.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<bool> QueryIsAllowed(int queryId, ClaimsIdentity identity)
Please add the `Async` suffix to the name of this method.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<string> GetCachedQuery(int queryId, ClaimsIdentity identity)
Please add the `Async` suffix to the name of this method.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<string> AddCachedQuery(int queryId, ClaimsIdentity identity)
Please add the `Async` suffix to the name of this method.

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                if (!QueryIsAllowed(style.QueryId, identity).Result)
Never use `.Result` on an async functions, that causes deadlocks, memory leaks etc. Please change this to:
```c#
if (!await QueryIsAllowed(style.QueryId, identity))
```

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        /// <returns>Returns <see cref="stlyedoutputmodel"/> of the added id.</returns>
Please fix your documentation. There is no class or object called `styledoutputmodel` (at least not al lower case). The `<see cref="x" />` element is meant to reference other, existing, classes. So make sure that the value you enter there is actually something that exists somewhere in the code.

Rider warns you about this, please don't ignore these warnings:
![image](https://github.com/user-attachments/assets/c19a83c0-00d6-4f8d-8bd0-ab42cff7aac6)

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        /// <returns>Returns <see cref="stlyedoutputmodel"/> of the requested id.</returns>
Please fix your documentation. There is no class or object called `styledoutputmodel` (at least not al lower case). The `<see cref="x" />` element is meant to reference other, existing, classes. So make sure that the value you enter there is actually something that exists somewhere in the code.

Rider warns you about this, please don't ignore these warnings:
![image](https://github.com/user-attachments/assets/c19a83c0-00d6-4f8d-8bd0-ab42cff7aac6)

2024-07-18 11:53 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
>          private Dictionary<int, List<Stopwatch>> timings = new Dictionary<int, List<Stopwatch>>();
Please fix the naming of these fields and make the arrays/dictionaries readonly. Rider gives suggestions for this, don't ignore those (if you have our code conventions setup correctly in Rider):
![image](https://github.com/user-attachments/assets/f41eee95-8ab4-4a55-ae57-3b73d82df10f)

2024-07-22 11:23 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
there was already a logger in the calling parent function but i guess never hurts to have more logging, added :)

2024-07-22 11:23 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
there was already a logger in the calling parent function but i guess never hurts to have more logging, added :)

2024-07-22 11:24 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +            var query = GetCachedQuery(style.QueryId, identity).Result;
Ah I see, thought .Result did this implicit but i guess not :)

2024-07-22 11:24 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<StyledOutputModel> GetCachedStyle(int id)
done

2024-07-22 11:24 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<StyledOutputModel> AddCachedStyle(int id)
done

2024-07-22 11:24 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        private async Task<string> AddCachedQuery(int queryId, ClaimsIdentity identity)
done

2024-07-22 11:25 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                if (!QueryIsAllowed(style.QueryId, identity).Result)
done

2024-07-22 11:25 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        /// <returns>Returns <see cref="stlyedoutputmodel"/> of the added id.</returns>
forgot to update that, done now,

2024-07-22 11:25 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +        /// <returns>Returns <see cref="stlyedoutputmodel"/> of the requested id.</returns>
forgot to update that, done now,

2024-07-22 11:25 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
>          private Dictionary<int, List<Stopwatch>> timings = new Dictionary<int, List<Stopwatch>>();
done

2024-07-22 12:58 UTC, GilianJuice requested changes

2024-07-22 12:58 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
This is not what I meant. Now you're still only logging `e.Message`. Please log the _entire_ exception, not just the Message. Your log should be something like this:
```C#
logger.LogError(e, "An error occurred while checking if a query is allowed to be executed.");
```
The first parameter is always for logging exceptions, the second is to add a message with more information.

2024-07-22 12:58 UTC, GilianJuice commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
This is not what I meant. Now you're still only logging `e.Message`. Please log the _entire_ exception, not just the Message. Your log should be something like this:
```C#
logger.LogError(e, "An error occurred while getting a cached style.");
```
The first parameter is always for logging exceptions, the second is to add a message with more information.

2024-07-23 07:08 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +                    ErrorMessage = e.Message
was unaware that the logger also eats exceptions, changes made per request :)

2024-07-23 07:10 UTC, MikeVanMourik commented
changed made per request

2024-07-23 07:17 UTC, GilianJuice approved these changes

2024-07-23 07:17 UTC, merged