Feature/javascript improvements 2
happy-geeks/wiser pull request #649
Opened 2024-07-31 16:08 UTC by MikeVanMourik

# Describe your changes

upgrading js to use more modern methods

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Upgrade

## How was this tested?

ran locally and comparing it with the wiserdemo on the side (as far as i can test on that since not everything on the demo site seems to work) 

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

# Link to Asana ticket

https://app.asana.com/0/1204371236183532/1205853947344178/f

2024-08-01 14:08 UTC, GilianJuice requested changes

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/sub-entities-grid.js
> -                    click: function(event) { window.dynamicItems.grids.onDeleteItemClick(event, this, options.deletionOfItems, options); }
Why did you add the `this` keyword to `options`? That isn't needed. `Options` is a variable defined in the outer scope, so nothing changes for that variable by making this into an arrow function.

Have you tested this change? If it works then it's okay, but it wasn't needed. Same thing with other places below, where you also changed `options` to `this.options`.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/sub-entities-grid.js
>  ﻿(function() {
You forgot to change this to an arrow function. You did it for other files.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/sub-entities-grid.js
This javascript still uses a lot of `.then()` and `.catch()`. It's not bad per se, but the code can be made much more readable if this is refactored to async/await and a normal try/catch. Can you see if you can do this? I can help if you have issues with it.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/sub-entities-grid.js
>                              }).then(function (customQueryResults) {
You forgot to change this to an arrow function.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/sub-entities-grid.js
>              change: function (e) {
You forgot to change this into an arrow function.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/textbox.js
>  ﻿(function() {
You forgot to change this into an arrow function.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/timeline.js
>  ﻿(function () {
You forgot to change this into an arrow function.

2024-08-01 14:08 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/timeline.js
> +                    let itemId = $(this).closest(".timelineEvent").data("itemid");
The `this` keyword doesn't work the same anymore in an arrow function. This line should be changed to this:
```javascript
let itemId = $(event.currentTarget).closest(".timelineEvent").data("itemid");
```

2024-10-10 11:42 UTC, MikeVanMourik commented
this pull request is a lot of work since im making changes, testing and because of only getting a little bit of time for it also includes rebases, so to make things less confusing ill place this PR into Drafts. ill take it out when its ready for another review round.

2025-05-19 07:42 UTC, MikeVanMourik commented
Everything in this pull request has now either been done or has its own pull request. im closing this PR (finally)

2025-05-19 07:42 UTC, closed without merging