create new end point for accessing styled outputs by name
happy-geeks/wiser pull request #650
Opened 2024-08-01 12:09 UTC by MikeVanMourik

# Describe your changes

because we are going to change the styled output table to use auto increment for its ids we added the function to use the name instead to find styled outputs

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

ran locally with postman

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable
note: i made a task to remind me to update the documentation once this is in

# Related pull requests

# Link to Asana ticket

Jira

2024-08-07 07:53 UTC, HansHappyHorizon requested changes
Found some issues with the code. Please fix these.

2024-08-07 07:53 UTC, HansHappyHorizon commented on Api/Modules/Queries/Controllers/StyledOutputController.cs
> +        public async Task<IActionResult> GetStyledOutputResultJson(string name, [FromBody] List<KeyValuePair<string, object>> parameters, bool stripNewlinesAndTabs = false,[FromQuery] int resultsPerP
This method is async, so the name should be `GetStyledOutputResultJsonAsync`. Please update the name.

2024-08-07 07:53 UTC, HansHappyHorizon commented on Api/Modules/Queries/Interfaces/IStyledOutputService.cs
> +        ///
Please remove this empty comment line.

2024-08-07 07:53 UTC, HansHappyHorizon commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +n
I don't think this will compile, seeing as there's a random `n` here.

2024-08-07 09:41 UTC, MikeVanMourik commented on Api/Modules/Queries/Services/StyledOutputService.cs
> +n
correct, im guessing i hit my keyboard by accident after testing a compile, didnt notice it on the commit

2024-08-07 09:41 UTC, MikeVanMourik commented on Api/Modules/Queries/Interfaces/IStyledOutputService.cs
> +        ///
done

2024-08-07 09:41 UTC, MikeVanMourik commented on Api/Modules/Queries/Controllers/StyledOutputController.cs
> +        public async Task<IActionResult> GetStyledOutputResultJson(string name, [FromBody] List<KeyValuePair<string, object>> parameters, bool stripNewlinesAndTabs = false,[FromQuery] int resultsPerP
alrighty

2024-08-14 08:03 UTC, HansHappyHorizon approved these changes

2024-08-14 08:03 UTC, merged