Feature/create queries on main and branch
happy-geeks/wiser pull request #652
Opened 2024-08-06 06:49 UTC by MikeVanMourik

# Describe your changes

when creating queries on a branch we now also create them on the main sql server so that the ids are the same

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

ran it locally and tested on wiserdemo db

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

9,.... 9! 9! 9!

# Link to Asana ticket

Jira : CON-278

2024-08-13 06:48 UTC, MarkVanDijkHG requested changes

2024-08-13 06:48 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/QueriesService.cs
> +            var createInBothDatabases = onBranch;
Please combine both variables. The comment would still be applicable (please use a capital letter and a period).

2024-08-13 06:48 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/QueriesService.cs
> +                var entityTypeSettings = await wiserItemsService.GetEntityTypeSettingsAsync("Query");
The queries are not from an entity, so it will also not get a prefix. If someone would make an entity for Query this would cause unexpected problems.

2024-08-13 06:48 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/QueriesService.cs
> +                                     {tablePrefix}{WiserTableNames.WiserIdMappings} WRITE
Wiser ID mappins also never has a prefix.

2024-08-13 06:48 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/QueriesService.cs
> +                    var itemInsertQuery = $@"INSERT INTO {WiserTableNames.WiserQuery}
Please move this to a function that requires the database connection to use. Currently the same code is used twice when on a branch and once when not a banch. See https://github.com/happy-geeks/wiser/blob/develop/Api/Modules/Files/Services/FilesService.cs#L385 as example.

2024-08-13 06:48 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/QueriesService.cs
> +        private async Task<int> GenerateNewIdAsync(string tableName, IDatabaseConnection mainDatabaseConnection, IDatabaseConnection branchDatabase)
Since changes need to be made, this function has been made available in https://github.com/happy-geeks/wiser/blob/develop/Api/Modules/Branches/Services/BranchesService.cs#L1926.

2024-08-13 14:07 UTC, MikeVanMourik commented
I made changes to this to change the entire flow, we now have the same flow for all cases:. 
making a entry when just on main
making a entry when on a branch on the branch db
making a entry when on a branch on the main db

2024-08-15 05:46 UTC, MarkVanDijkHG requested changes

2024-08-15 05:46 UTC, MarkVanDijkHG commented on Api/Modules/Queries/Services/QueriesService.cs
> +                await targetDatabase.ExecuteAsync(lockQuery);
You are currently only locking 1 table when creating the item. The lock is meant to prevent changes in both databases to ensure the ID stays available in both databases that could happen due a race condition.

2024-08-21 14:35 UTC, MikeVanMourik commented
done

2024-08-22 05:40 UTC, MarkVanDijkHG approved these changes

2024-08-22 05:41 UTC, merged