add function to create a dataselector on both main and branch when br…
happy-geeks/wiser pull request #669
Opened 2024-08-09 08:58 UTC by MikeVanMourik

# Describe your changes

when creating a dataselector on a branch this will also be created on main to ensure we have the same ids

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?
locally ran connecting to wiser_demo

Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

noooo

# Link to Asana ticket

JIRA CON-279

2024-08-13 06:52 UTC, MarkVanDijkHG requested changes

2024-08-13 06:52 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +                var createOnBranchAndMain = onBranch;
Please combine both variables. The comment would still be applicable (please use a capital letter and a period).

2024-08-13 06:52 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +                    mainDatabaseConnection.AddParameter("name", data.Name);
Please move this to a function that requires the database connection to use. Currently the same code is used twice when on a branch and once when not a banch. See https://github.com/happy-geeks/wiser/blob/develop/Api/Modules/Files/Services/FilesService.cs#L385 as example.

2024-08-13 06:52 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +        private async Task<int> GenerateNewIdAsync(string tableName, IDatabaseConnection mainDatabaseConnection, IDatabaseConnection branchDatabase)
Since changes need to be made, this function has been made available in https://github.com/happy-geeks/wiser/blob/develop/Api/Modules/Branches/Services/BranchesService.cs#L1926.

2024-09-11 09:39 UTC, MikeVanMourik commented
this has finally been updated to conform to same approach we did for query saving, so seperate functions and using the generatenewid function from the branchservice

2024-09-17 13:40 UTC, MarkVanDijkHG requested changes

2024-09-17 13:40 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +        private async Task<int> GenerateNewIdAsync(string tableName, IDatabaseConnection mainDatabaseConnection, IDatabaseConnection branchDatabase)
The general method is now used but the method in this file needs to be cleaned up.

2024-09-17 13:40 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +                await databaseHelpersService.CheckAndUpdateTablesAsync(new List<string> {WiserTableNames.WiserIdMappings});
Wiser ID mappings is needed on the branch database. Now it will also be created on the main database. This might have been added due to the reused lock query needs to lock it, but the table doesn't seem to be used further in the file. It might not be needed here since these IDs will always be matched when created on the branch instead of optional as with the items (that does insert a record in the mappings).

The same applies for the query service.

2024-09-17 13:40 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +                var newId = (int)await branchesService.GenerateNewIdAsync(WiserTableNames.WiserDataSelector,
A new ID here is generated while this was already done before calling the function and placed in data.Id. Now it can go good but also wrong. Please use the ID previously generated.

2024-09-17 13:40 UTC, MarkVanDijkHG commented on Api/Modules/DataSelectors/Services/DataSelectorsService.cs
> +        private async Task<ServiceResult<int>> SaveAsyncOnDataBase(IDatabaseConnection targetDatabase, DataSelectorModel data, ClaimsIdentity identity)
Please add a new line between the two methods.

2024-09-20 06:04 UTC, MarkVanDijkHG approved these changes

2024-09-20 06:04 UTC, merged