Bugfix in linking items when current item is source
happy-geeks/wiser pull request #737
Opened 2024-10-14 11:22 UTC by rvdgraaf

# Describe your changes

Fixed bug when linking items with sub-entities-grid and current item is source. The wrong entity type was sent to the Wiser API. The Wiser API then did not create a link.

## Type of change

Please check only ONE option.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

Tried to create a link without this fix. The link is not created. Tried again after making the changes. Link has been created.

# Checklist before requesting a review
- [X] I have reviewed and tested my changes
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [X] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [X] I added new unit tests for my changes if applicable

# Related pull requests

N/A

# Link to Asana ticket

https://app.asana.com/0/1201027711166952/1206120608401144

2024-10-16 08:29 UTC, HansHappyHorizon requested changes
Code looks okay to me, but I have one concern in one of the changes. Could you address this concern, and update the code if you agree?

2024-10-16 08:29 UTC, HansHappyHorizon commented on FrontEnd/Modules/DynamicItems/Scripts/Windows.js
> +            else {
I wonder if this `else` clause is necessary. The original code only set the `sourceEntityType` on the `addLinksRequest` and `removeLinksRequest` objects if `currentItemIsSourceId` is set to `true`, so I think only the `if` statement needs to be updated. Now the functionality has been extended without knowing what side-effects this might have.

Just to be safe, I think it might be a good idea to remove the `else` clause.

2024-10-28 10:00 UTC, rvdgraaf commented on FrontEnd/Modules/DynamicItems/Scripts/Windows.js
> +            else {
The else clause is not absolutely necessary, but it did make it clearer how things work. I deleted it.

2024-10-28 10:21 UTC, HansHappyHorizon approved these changes

2024-10-28 10:21 UTC, merged