perform javascript improvements/cleanup in ImageUpload.js
happy-geeks/wiser pull request #796
Opened 2024-12-10 15:31 UTC by MikeVanMourik

# Describe your changes

I am making javascript improvements to get better at javascript,
because https://github.com/happy-geeks/wiser/pull/649
was getting too much all at once i decided to break these prs up per file.

## Type of change

Please check only ONE option.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

locally on wiserdemo db

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

this is the old one ( it does not to checked or merged, its just for ref):
https://github.com/happy-geeks/wiser/pull/649

# Link to Asana ticket

https://app.asana.com/0/1204371236183532/1205853947344178/f

2024-12-12 13:47 UTC, GilianJuice requested changes

2024-12-12 13:47 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/image-upload.js
> +            let apiResult = Wiser.api({
This will probably not work correctly. You forgot to add `await` here. So if an error occurs during the API request, then the function will already be finished and the `catch` will never be hit, because you don't wait for the API request.

2024-12-12 13:47 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/image-upload.js
> +        try{
Please add a space between `try` and `{`.

2024-12-18 10:00 UTC, MikeVanMourik commented on Api/Modules/Items/FieldTemplates/image-upload.js
> +            let apiResult = Wiser.api({
yeah.. that makes no sense, nice catch thank you

2024-12-18 10:05 UTC, GilianJuice approved these changes

2024-12-18 10:05 UTC, merged