perform javascript improvements/cleanup in item-linker.js
happy-geeks/wiser pull request #803
Opened 2024-12-11 15:00 UTC by MikeVanMourik

# Describe your changes

I am making javascript improvements to get better at javascript,
because https://github.com/happy-geeks/wiser/pull/649
was getting too much all at once i decided to break these prs up per file.

## Type of change

Please check only ONE option.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

locally on wiserdemo db

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [x] I added new unit tests for my changes if applicable

# Related pull requests

this is the old one ( it does not to checked or merged, its just for ref):
https://github.com/happy-geeks/wiser/pull/649

# Link to Asana ticket

https://app.asana.com/0/1204371236183532/1205853947344178/f

2024-12-12 13:52 UTC, GilianJuice requested changes

2024-12-12 13:52 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/item-linker.js
> +                var treeView = $(checkTreeElement).data("kendoTreeView");
You forgot to change `var` to `const` here.

2024-12-12 13:52 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/item-linker.js
> +        checkTreeElement.find(".k-in:contains(" + filterText + ")").each( (index, element) => {
You forgot to replace the string concatenation with a template string here. Also, please remove the space between `each(` and `(index`.

2024-12-12 13:52 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/item-linker.js
>  }).then(function (customColumns) {
You forgot to change this to an arrow function.

2024-12-12 13:52 UTC, GilianJuice commented on Api/Modules/Items/FieldTemplates/item-linker.js
> +                        }
Why are the brackets indented more than the `catch`? Please fix. Or did you use tabs instead of spaces here?

2024-12-18 10:29 UTC, GilianJuice approved these changes

2024-12-18 10:29 UTC, merged

2024-12-18 10:30 UTC, MikeVanMourik commented on Api/Modules/Items/FieldTemplates/item-linker.js
> +                var treeView = $(checkTreeElement).data("kendoTreeView");
I did

2024-12-18 10:31 UTC, MikeVanMourik commented on Api/Modules/Items/FieldTemplates/item-linker.js
> +        checkTreeElement.find(".k-in:contains(" + filterText + ")").each( (index, element) => {
killed it

2024-12-18 10:32 UTC, MikeVanMourik commented on Api/Modules/Items/FieldTemplates/item-linker.js
>  }).then(function (customColumns) {
what is that behind you?! 
-quickly changes it into a arrow function when you were not looking-
no idea what you are talking about

2024-12-18 10:32 UTC, MikeVanMourik commented on Api/Modules/Items/FieldTemplates/item-linker.js
> +                        }
not sure what happened there, guessing rider "helped", its back to normal